### ISSUE TITLE
Question: How do you indicate tools for manual testing

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#112]
Tools are often used to assist manual testing. How should this be described in the ACT Rules Format?

**Comment by WilcoFiers** [comment]
Proposed solution: We can track which tools have a rule implemented. We need to know this anyway since we want a certain number of implementations before we make the rule 'official'. This list could be used as a list of tools that can be used for the rule.

**Comment by maryjom** [comment]
@WilcoFiers We need a way for tools providers to document/provide a link to the documentation for their support of the ACT rules. This will be outside of the specification and not part of the rules format.

**Comment by WilcoFiers** [comment]
As @maryjom This issue is outside the scope of ACT Rules format, so I'm closing the issue.
