### ISSUE TITLE
Clarify the purpose of the test procedure

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#113]
Some questions came up during the ACT call about the goal of the test procedure. Conclusion was that it should be clearer that tools aren't expected to follow the exact steps of the test procedure, as long as the results are consistent. The purpose of the test procedure is to give users of ACT Rules and users of accessibility tools that use ACT rules enough detail to know if the rule would be usable and reliable enough for their needs.

**Comment by nitedog** [comment]
Specific suggestion was to add something along these lines to the ACT Rules Format spec and template for the ACT Rules:

> Programming code within tools and manual evaluation carried out by humans may deviate from these exact steps, but must consistently return the expected results defined by this procedure.

**Comment by maryjom** [comment]
@WilcoFiers Have the changes been incorporated for this?  Wondering if there's still work to do on this or if we can close this issue.

**Comment by WilcoFiers** [comment]
Since we've moved away from selector/steps to applicability/expectations, we won't need to add this clarification.
