### ISSUE TITLE
Support for recording state in output data

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#114]
In DOM Tree testing scripts are applied so that the test subject can be in "a specific state (be it the initial state or any other)" (Section 4.1).

This could affect the position of an element in the DOM. Please elaborate how is this recorded in the output data. Two options come to mind:

(1)  A pointer can be used to indicate where the selected item exists within the web page or other test subject. The pointer method used in the output data of an ACT Rule must include the pointer method used in Implementation Test Cases.

OR (2) As part of the test subject

**Comment by nitedog** [comment]
This is not directly part of the ACT Rules Format, but the related output format based on EARL that we are looking at developing to support the test cases (likely a JSON serialization of EARL).

In EARL, the specific state is recorded as part of the test subject. For example, stating the DOM Tree as the test subject, or by including the HTTP exchanges to define the specific state of the web content. The pointers then refer to the position, item, or other identification within the test subject.

That is, the model of EARL maps to point (1) in your question above. Both the type of test subject and pointer method should be described in the output data.

**Comment by nitedog** [comment]
@annika-FTB please see the response above and feel free to re-open, as needed.
