### ISSUE TITLE
Terminology in Section 8 ACT Data Format 

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#115]
8.1 introduces the term "selected item" to refer to the object to which the test procedure is applied. In 8.2 the term "test target" is introduced. Why are two terms needed? What is the difference?

**Comment by WilcoFiers** [comment]
Good point. The two are identical. We should make this more consistent.

**Comment by WilcoFiers** [comment]
RESOLUTION: We're going with test target. We'll add a definition to this as well.
