### ISSUE TITLE
Output data format for rule groups

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#116]
How is the output data format extended to cover the output data for rule groups?

Especially if rules within the same rule group can have different selectors how are the individual rule output data grouped into rule groups output data? 

The subject is too coarse because a rule group might be applicable several times (e.g. several tables within a web page). On the other hand the pointer (i.e. selected item) is not suitable either because "rules in a group MAY have different selectors."

**Comment by rdeltour** [comment]
Defining the output data depends on improving/stabilizing the definition of rule groups, for instance (do we allow a group to require more than one pass?). 

Let's discuss this first, in other issues, then get back to the output data definition.

**Comment by WilcoFiers** [comment]
This issue has been resolved by moving to composed rules. Thanks for the feedback Annika!
