### ISSUE TITLE
Consistency: Possible outcome values

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#117]
Section 5.2 states that a test case result is "passed or failed". The outcome (Section 8.2) lists three possible values "Passed, Failed or Undetermined".

**Comment by josehilera** [comment]
why not use "cannot tell" instead "undetermined" as in EARL 1.0 (hthttps://www.w3.org/TR/EARL10-Schema/#OutcomeValue )?

why not used also "Innaplicable" as another outcome value as in EARL 1.0. ?

**Comment by WilcoFiers** [comment]
Decision: Use cantTell and we'll a definition for it, one that's better than the one in earl.
