### ISSUE TITLE
Recommendation for Accuracy Benchmarking (Section 9.2)

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#118]
Studies on inter-evaluator agreement report results lower than 100% ([W3C Research Report](http://www.w3.org/TR/accessibility-metrics-report/)).

It seems unrealistic to define "the expert" as gold standard. Especially when taking into account that experts need to learn about new ways to create accessibly content as well as tools - although not in the same manner.

Instead of asking a single expert a statistics approach (collecting false positive and false negative reports from the users of a test tool) might be more suitable. Although one has to be careful not to mix this up with the validation of an implementation.

**Comment by WilcoFiers** [comment]
We've had a discussion about this. I don't think we can do much about this point for manual steps. Human testers can always get things wrong. This simply means that no manual rule can ever be 100% accurate, which I think is alright.
