### ISSUE TITLE
Suggestion for 8. ACT Data Format (Output Format) - Sufficient Technique(s)

### ISSUE THREAD

**Issue by goodwitch** [w3c/wcag-act#126]
[8. ACT Data Format (Output Format)](https://www.w3.org/TR/act-rules-format/#output) - Sure would be cool if we could optionally include sufficient techniques that solve the problem when **this** rule is failed.  I understand...this may be out of scope.

**Comment by nitedog** [comment]
From [ACT TF meeting on 7 December 2017](https://www.w3.org/2017/12/07-wcag-act-minutes.html): remediation is out of scope of ACT Rules Format 1.0 but we may consider this as suggestion for future improvement to [EARL](https://www.w3.org/WAI/intro/earl).

**Comment by nitedog** [comment]
Coming to think of it, [EARL info](https://www.w3.org/TR/EARL10-Schema/#info) allows results to include (plain text) messages. These could include warning or remediation information. However, this really depends on the evaluation tool, human, and process that can provide such guidance. It is out of scope of ACT.

**Comment by nitedog** [comment]
@goodwitch please see the response above and feel free to re-open, as needed.
