### ISSUE TITLE
In 3.1, “written in plain language” sounds awkward for some of the Rule's items

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#132]
Section [3.1 Rule Outline](https://w3c.github.io/wcag-act/act-rules-format.html#structure-outline) currently reads:

> Each ACT Rule MUST provide the following items written in plain language:
> * …
> * Unique identifier
> * …
> * Test Subject Type

This sounds slightly confusing to me (what does it mean to write a unique identifier in plain language?).

I suggest to reword into:

> An ACT Rule MUST be written in plain language. It MUST consist of the following items:
> * …

**Comment by maryjom** [comment]
Editorial change made and merged.
