### ISSUE TITLE
[editorial] Harmonize language on how ACT Rules conformance

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#134]
the spec uses various forms of statements to specify what an ACT Rule must look like, for instance:

- RFC2119 statements (like "Each ACT rule must") in sections 3.1, 3.2, 3.3
- imperative mood in section 3.4 ("List any limitations")
- descriptive statement in section 5.2 ("Each rule contains")

The spec language could be a bit more consistent, and use RFC 2119 keywords where needed.

**Comment by maryjom** [comment]
It needs an editorial scrub for these things and decide where we really want to use the MUST, MAY language.
