### ISSUE TITLE
Example of section 3.4 “Limitations, Assumptions, or Exceptions”

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#136]
I find the example given in section 3.4 not very obvious:

> For example, A rule for Success Criterion 1.4.1: Use of Color has to make an assumption that CSS is used to make a link visually evident - typically by using CSS background, border, color, font, or text-decoration properties.

The path from SC 1.4.1 to requiring CSS to make a link visually evident isn't obvious for one not versed in WCAG/HTML. Also, a rule could be partially based on SC 1.4.1 and not require parsing CSS at all.

**Comment by maryjom** [comment]
Romain will come up with a better example to incorporate into the spec.

**Comment by rdeltour** [comment]
Here's a proposed example:

> For example, a rule that would partially test WCAG 2.0 Success Criterion 1.4.3 (minimum contrast) could state that it only applies to HTML text content stylable with CSS and does not support images of text.

WDYT?
