### ISSUE TITLE
Spec sections ordering is not consistent with the Rule outline

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#137]
In the Rule outline defined in section 3.1, item "Accessibility support" (section 7) is between "Limitations" (section 3.4) and "Test subject type' (section 4).

Could we consider moving the section so that the spec outline is consistent with the rule’s outline?

**Comment by moekraft** [comment]
This was addressed by PR #147

**Comment by moekraft** [comment]
This change was approved at today's WCAG ACT TF meeting, 11/30/17.
