### ISSUE TITLE
Better example for non-DOM selector?

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#138]
Section "5.1 Selector" currently reads:

>  For example (…) finding tags that are incorrectly closed in an HTML document.

The forgiving HTML parser would probably work its way around those, is this selector used in a known accessibility testing rule?
If no, I'd suggest maybe finding another concrete example?

In any case, I'd replace "HTML document" by "serialized HTML document" to make sure we're talking about the raw bytes here, and not the parsed document.

**Comment by maryjom** [comment]
Assigned to Stein-Eric as an action since he's not in github yet.
