### ISSUE TITLE
Consider a new section on "Evaluating a Rule"?

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#139]
While reading the draft for the nth time, it occurred to me that several sections conflate statements on the Rules’ **format** and on how a Rule is **processed**.

A typical example is section 5.2 "Text ~~Cases~~Execution steps":

The following part is a statement on the Rule format
> Each rule contains one ore more test execution steps

While the next paragraph is about how the Rule is processed:
> Test execution steps results are combined with other test execution steps results to provide a cumulative outcome

What about removing all the spec parts related to processing, and move them in a common section "Rule processing".  That would make the other sections just descriptive and simpler. In addition, that "Processing" section could use some non-ambiguous pseudo-code syntax to define the processing algorithm, and could help making the processing more clear and precise.

Thoughts? I'm happy to work on a draft PR if the group thinks it's a good idea.

**Comment by moekraft** [comment]
Discussed with Romain. We would like to wait to see where we were going wrt "selector" vs/ "applicability" first (as we discussed this past few weeks).

**Comment by rdeltour** [comment]
I revisited this proposal: 

The idea is basically to explain how the evaluation of a rule (or rule group) results in the output format (the exact implementation is dependent on the tool, but the spec should guarantee that for a same rule and same test subject, all the tools will provide the same outcome).

As it is, the proposed change would be mostly editorial (move in their own section some statements or text that are currently in other sections about the rule description or outcome description). But in fact it still depends on reaching conclusions in other discussion on the output format (#162, #207) and rule groups (#116, #209).

When the rule groups and outcome formats are stable, I will see if it makes sense, editorially, to propose this new section.

**Comment by WilcoFiers** [comment]
@rdeltour Do you still intend to work on this? If not I propose we close the issue.

**Comment by rdeltour** [comment]
@WilcoFiers let's keep that open for a little while longer; as we discussed on [Sept 6](https://www.w3.org/2018/09/06-wcag-act-minutes.html) some statements are on the implementations (whereas the rest of the statements are on the Rule authors), and the output format needs to be clarified. These issues are directly impacting this issue/proposal, so I'd like to see where we're going before closing 😄
