### ISSUE TITLE
Comparison of different Test Case Design frameworks

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#16]
Forwarded with permission - useful previous work for ACT TF to look at:

On 05-Dec-16 9:00, Carlos A Velasco wrote:
> The Test Case Description Language has been published (open source'd) a
> while ago in GitHub. See:
>
> https://github.com/webcc/bentoweb-tcdl
>
> As you remember (also from the 2nd version in the W3C space), it is
> based on a XML schema. With a perspective of almost 10 years, I would
> have chosen a RDF approach now, but I have no time machine at hand ;)
> Anyway, I think it is a good basis to build a semantic vocabulary.
>
> All the test suites built upon that vocabulary are in our GitHub
> repository, with the prefix "bentoweb-*":
>
> https://github.com/webcc

-- 
Shadi Abou-Zahra - http://www.w3.org/People/shadi/
W3C Web Accessibility Initiative (WAI)

**Comment by WilcoFiers** [comment]
I need to add BenToWeb to the comparison

**Comment by WilcoFiers** [comment]
Work was resolved here: https://www.w3.org/WAI/GL/task-forces/conformance-testing/wiki/Testing_Resources
