### ISSUE TITLE
Clarify the output format definition

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#162]
Section [ACT Data Format (Output Data)](https://w3c.github.io/wcag-act/act-rules-format.html#output) says that a rule’s execution should 

> return a set of zero or more results each of which MUST have at least the following properties:
> - test (rule ID)
> - subject (Web page)
> - pointer (Test target)
> - outcome (Passed or Failed)

I find that this lacks clarity in several aspects:

- the `test` and `subject` properties are the same for all the test targets, do they have to be repeated in all the test targets’ individual results?
- does it mean that the test output should contain the individual results for **all** the individual tests targets, even when they pass? A single global `pass` outcome may be preferable over having potentially thousands of individual `pass` outcomes, one for each target).
- can we define the result in a more structured manner: a global outcome + a collection of individual outcomes for failing test target?
- the `outcome` is defined here as "passed or failed" where it later is described as accepting also the value "Inapplicable" (in 8.2).

Section [8.2 Outcome](https://w3c.github.io/wcag-act/act-rules-format.html#output-outcome) says:

> The procedure of a rule MUST always return one of the following outcomes

This apparently applies to the global outcome, but this concept is not explained clearly in the introduction of the "ACT Data Format" section.

Section [8.3 Ensure comparable results](https://w3c.github.io/wcag-act/act-rules-format.html#output-comparable) says:

> ACT Rule output data MUST include (…) the Web page, file or other test subject the rule was applied to

which is somewhat contradictory with the following section explaining that only a pointer will do.

Section [8.4 Test subject](https://w3c.github.io/wcag-act/act-rules-format.html#output-test-subject) is really about the `pointer` property of the outcome, so it should be made more explicit.

**Comment by WilcoFiers** [comment]
I'll add an editors note indicating how much detail we need from the output format.
