### ISSUE TITLE
Clarify how to do "Implementation validation" and "accuracy benchmarking" for manual or semi-automated rules

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#163]
Section [9.1 Implementation validation](https://w3c.github.io/wcag-act/act-rules-format.html#quality-implement) says:

> Implementation tests are tests for accessibility test tools. These tests enable the developers and users of ATTs to validate the implementation of an ACT Rule.

Section [9.2 Accuracy benchmarking] says:

> In benchmark testing, the accuracy of a rule is measured, by comparing it’s results to those obtained through accessibility expert testing.

and

> For instance, accessibility test tools can implement a feature which lets users indicate that a result is in error, or pages that for which accessibility results are known, can be tested using ATT, and the results are compared. To compare results from ACT Rules to those of expert evaluations, data aggregation may be necessary.

This sounds like these sections only apply to automated rules, as implemented by ATT.
Given that our format also covers manual test rules, this should be clarified.

**Comment by WilcoFiers** [comment]
Conclusion from the group: We're removing the accuracy benchmark section, keep the definitions about false positives / false negatives in a separate section.

**Comment by maryjom** [comment]
Need to get with Moe to decide where to put those definitions.
