### ISSUE TITLE
Better define how to test the applicability part of a rule

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#164]
Section [9.1 Implementation validation](https://w3c.github.io/wcag-act/act-rules-format.html#quality-implement) says:

>  Each rule MUST have implementation tests for the _applicability_ (…)

and then in the following paragraph:

> An implementation test consists of two parts: a piece of input data and an expected result. When applying the test, the piece of input data, for instance an HTML code snippet, is evaluated by following the rule’s test procedure. 

This definition of a test can’t be used to test the applicability only.
We should consider defining two types of tests:
- `applicability` tests (takes an input data and an expected set of test targets)
- `expectation` tests (takes an input set of tests targets and expected set of results)

**Comment by WilcoFiers** [comment]
We'll revisit this. I don't think this needs an editor's note.

**Comment by WilcoFiers** [comment]
The group believes these types of tests do make sense, but should not be part of the specification.
