### ISSUE TITLE
Consider linking from the spec to GitHub issues

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#166]
The draft currently contains several editor notes to explain where we’re looking for feedback. I believe it would also be very useful to contain actual pointers to key GitHub issues wherever there’s an open discussion or work in progress.

See for instances how it’s done in the [Web App Manifest](https://w3c.github.io/manifest/) spec or the the [Web Publications](https://w3c.github.io/wpub/#) draft.

**Comment by WilcoFiers** [comment]
I've done this in the newest draft.
