### ISSUE TITLE
Review process comments Detlev Fischer

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#174]
== Overall feedback (Detlev) ==
The whole document sounds pretty stern and not very inviting (if getting voluntary contributions from the community are a real aim).

===Step 1: ACT Rule Creation===
(Detlev): 

* link "file naming conventions" from this text?
* Link to the relevant Github repository?
* It sounds pretty daunting to say "Contributors are responsible for ensuring that their contributions adhere to these requirements at all times" - if you want more rules, wouldn't it be good to have a more inviting approach - even a rule in pseudo code that does not adhere strictly to agreed format (which takes time to learn) would be a worthwhile contribution?

=== Step 4: ACT Rule Implementation ===

(Detlev): 

I think "Implementation manifests" needs some explanation, may be a link to an explanation - I would not be sure what I would have to do if I considered referencing particular rules in our manual test procedure (manual testing is explicitly incuded as iplementation context).

=== Step 5: ACT Rule Maintenance ===
(Detlev):

I was a bit unsure whether the sentence "Implementations for ACT Rules may be added, modified, or removed at any time." applies to implementations of third parties (so saying 'do as you like, use what feels fit') or to some centrally maintained rule base at WAI.

Does the text need to say anything about implementers' scope for modifying rules in the way they are implemented in their tools or processes, or about any constraints on that, at least regarding claims that they 'use the ACT rule base' or similar?

**Comment by nitedog** [comment]
DRAFT RESPONSE:

> The whole document sounds pretty stern and not very inviting (if getting voluntary contributions from the community are a real aim).
> [...]
> (Step 1) It sounds pretty daunting to say "Contributors are responsible for ensuring that their contributions adhere to these requirements at all times" - if you want more rules, wouldn't it be good to have a more inviting approach - even a rule in pseudo code that does not adhere strictly to agreed format (which takes time to learn) would be a worthwhile contribution?

We will look at making the document more inviting to read. However, it is not the intent of this review process to have people suggest pseudo code or less mature rules. The intent is to ensure a rigorous process that will result in vetted and widely accepted ACT Rules.

> link "file naming conventions" from this text?

This will be developed in future iterations of this document (see "to-do" at the bottom of the page).

> Link to the relevant Github repository?

This process could apply to different groups, each with their own repository. Currently Auto-WCAG exists but it is imaginable there may be a separate digital publishing group following this same process but with a different repository. We will try to better clarify this in the introduction.

> I think "Implementation manifests" needs some explanation, may be a link to an explanation - I would not be sure what I would have to do if I considered referencing particular rules in our manual test procedure (manual testing is explicitly incuded as iplementation context).

This will be developed in future iterations of this document (see "to-do" at the bottom of the page).

> I was a bit unsure whether the sentence "Implementations for ACT Rules may be added, modified, or removed at any time." applies to implementations of third parties (so saying 'do as you like, use what feels fit') or to some centrally maintained rule base at WAI.

It is the former - the situation regarding the implementation of ACT Rules is expected to change over time, and there needs to be a maintenance concept for this. We will improve the wording in future iterations of the document.

> Does the text need to say anything about implementers' scope for modifying rules in the way they are implemented in their tools or processes, or about any constraints on that, at least regarding claims that they 'use the ACT rule base' or similar?

The underlying assumptions is that implementations claims apply to the published ACT Rules and their test cases, not any derivatives of them. This will be clarified in the description of the "implementation manifest" that is to be developed (see response to related comment).

**Comment by WilcoFiers** [comment]
1. Implementors can update their manifest at their own pace
2. Implementers MUST implement the rule as is, they aren't allowed to implement a variation of it

**Comment by WilcoFiers** [comment]
Also: We will be adding understanding documentation to help. See #180
