### ISSUE TITLE
Communicating the need for additional input for rules that may require such

### ISSUE THREAD

**Issue by kasperisager** [w3c/wcag-act#176]
While the current output data format is perfectly suited for rules that can be implemented in a fully automated manner, I feel that it lacks a way of communicating the need for additional input for rules that contain manual test procedures. I'm currently prototyping an API for implementing and executing manual rules and have ended up with the following compromise:

1. The rule is executed against the aspects defined by the rule.
2. For all test targets for which the rule needs input from an external source, a "failed" result is output in addition to one or more questions.
3. The result set is checked for "failed" results and associated questions. If questions are found, the external source is consulted for answers.
4. The rule is executed again with the answers from step 3 passed as input.
5. Repeat steps 2-4 until no more questions are present in the result set.

Could look like the following in code:

```ts
execute("r1", document)
// =>
[
    {
        test: "r1",
        question: "is-descriptive",
        pointer: <img alt="Howdy!" src="howdy.png">
    },
    {
        test: "r1",
        subject: document,
        outcome: "failed",
        pointer: <img alt="Howdy!" src="howdy.png">,
    }
]

// Get these from a person or your favourite TensorFlow model
const answers = [
    {
        test: "r1",
        question: "is-descriptive",
        pointer: <img alt="Howdy!" src="howdy.png">,
        answer: true
    }
]

execute("r1", document, answers)
// =>
[
    {
        test: "r1",
        subject: document,
        outcome: "passed",
        pointer: <img alt="Howdy!" src="howdy.png">,
    }
]
```

I know that the __CannotTell__ outcome was an attempt at tackling this issue. As discussed previously, I however think that an intermediate result type like the questions seen above is a better way of solving it as it keeps intermediate and final results as two separate entities.

Would there be any value in formalising an approach to expressing these intermediate results for manual rules?

**Comment by WilcoFiers** [comment]
I propose this is out of scope for the ACT Rules Format. This is more of an EARL question. @skotkjerra @kasperisager if you object, feel free to reopen the issue.

**Comment by kasperisager** [comment]
Agreed 👍
