### ISSUE TITLE
Editorial differences between spec and example rules

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag-act#179]
There are some nit picky editorial differences between the spec and the example rules, as follows:

Different order of sections:
- ACT Rule Structure outline (Section 3.1) has the order - Rule Description then Accessibility Requirements, but the example rules switch the order. 
- Rule Group section comes after Expectations section in the spec, but is after the Assumptions section in the rules.

Different heading names:
- Spec has 'Limitations, Assumptions or Exceptions' and example rule has 'Assumptions'.
- Spec has a section called "Accessibility Support" that does not appear in the example rules.
- Spec has a section called "ACT Test Procedure" but in rule it is called "Test Procedure". I think 'ACT' can be dropped in the heading in the spec.
- Spec calls subsection 'Expectations' and test rules say 'Expectation' which should be changed to 'Expectations'.
- Example rule says 'Changelog' instead of 'Change log'.
- Spec has a section called 'Rule Grouping' where the rules have the section "Rule Group". I like "Rule Group" better.

Difference in specified content:
- Spec specifies in the Change Log section that each release of an ACT rule MUST be identifiable with either a date or version number with the change.  Example rule has a change log, but no date or version number information. Additionally, a reference to the previous version of that rule MUST be available.  Have we shown in the example rules how that should/could be accomplished?
 
Other things I noted:
- Spec has an issues list section (optional).  Should rules have a placeholder section for that that says "No know issues" if there are none? Is there a placeholder for this section in the rule template?
- If the rule isn't part of a group, should the section exist in the rule and say "Not part of a rule group" or is the absence of the section better?
- The example rule has an acknowledgement section to show the writer(s) of the rule, but the spec contains no such section. Should it, as an optional part of the rule?
- The group number in the heading doesn't seem to match the group numbering scheme: The rules ACT-G1-R1, R2, R3 and R4 all have a heading for the Rule Group that is numbered different than the rule group.  Heading says "ACT-R3 Rule Group" when all of these rules are numbered ACT-G1-Rx.  So shouldn't the heading say "ACT-G1 Rule Group"?

**Comment by skotkjerra** [comment]
Assumptions correction is done in this PR https://github.com/w3c/wcag-act/pull/305/files
So is moving Accessibility support into an optional part of the rule structure

**Comment by nitedog** [comment]
@WilcoFiers @maryjom I think this can be closed?

**Comment by WilcoFiers** [comment]
I agree, closing.
