### ISSUE TITLE
Add rule groups

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#193]
- Rule groups should have their own pages, showing the rule group specifics, and what rules are contained within that rule group.
- Rule groups should be part of the rules table - rules that are part of a rule group should be shown as "contained within" the rule group.
- Rules that are part of a rule group should have navigation to make it easy to navigate between rules in the group, and the group page itself

**Comment by annethyme** [comment]
Suggesting to close https://github.com/w3c/wcag-act/issues/161 since that is being solved by this one.

**Comment by annethyme** [comment]
Issue on "Custom Aggregation for Rule Groups", https://github.com/w3c/wcag-act/issues/198, is related to this one.

**Comment by WilcoFiers** [comment]
Issue has been superseded by composed rules.
