### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#196]
To share definitions between rules, a glossary page will be added. The glossary contains a list of all defined terms in the rules.

**Comment by jkodu** [comment]
PR showing how glossary can be incorporated is here - https://github.com/auto-wcag/auto-wcag/pull/147
Did it in auto-wcag for early review.

**Comment by WilcoFiers** [comment]
Issue is being worked on in Auto-WCAG.
