### ISSUE TITLE
Example 1 and Example 2 are identical

### ISSUE THREAD

**Issue by annethyme** [w3c/wcag-act#197]
When looking for examples for our ACT Rules writing, I realised that our Example 1 and Example 2 in the ACT Rules Format are copy-pasted so that they exactly the same: 

"A rule for labels of HTML input elements may have the following expectations:
The test target has an accessible name (as described in Accessible Name and Description: Computation and API Mappings 1.1).
The accessible name describes the purpose of the test target."
(https://w3c.github.io/wcag-act/act-rules-format.html#applicability)

So we are in fact missing an example for Applicability.

**Comment by WilcoFiers** [comment]
This issue has since been resolved.
