### ISSUE TITLE
Custom Aggregation for Rule Groups

### ISSUE THREAD

**Issue by annethyme** [w3c/wcag-act#198]
It should be possible to define custom aggregation logic for Rule Groups, e.g. on the pages for the rule group (https://github.com/w3c/wcag-act/issues/193).

Examples of this need: 
- 2.4.5 Multiple Ways where passing requires "Using two or more of the following techniques:"
- 3.3.2 Labels or Instructions were passing one subsection of techniques requires "G131: Providing descriptive labels AND one of the following:"

**Comment by annethyme** [comment]
Proposed rewrite of Rule Groups section: https://github.com/w3c/wcag-act/pull/211/files

**Comment by WilcoFiers** [comment]
Rule groups have been replaced by composed rules, which address this issue.
