### ISSUE TITLE
DIFI: ACT Rule Data Format

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#206]
Outcome must be specified for each test target. Output data must not only include test subject and rule identifier, but also other information with which the test rule has been tagged. This provides a data material that is far richer.

**Comment by nitedog** [comment]
Conclusion from ACT TF discussion on 17 May 2018: nothing prevents someone from recording the outcome for each test target (each occurrence of pass/fail). However, this is not the usual way of reporting, therefore should not be a requirement.
