### ISSUE TITLE
DIFI: 8.3. Outcome

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#207]
The ACT rule outcomes do not map fully to EARL outcomes. EARL also has the outcomes Cannot tell (it is unclear if the subject passed or failed the test) and Untested (the test has not been carried out). In what way should the ACT rule format take these outcomes into account?

For outcome Failed: It must be possible to identify the result for each expectation in a rule, not only for all expectations combined.

**Comment by nitedog** [comment]
Conclusion from ACT TF discussion on 17 May 2018: these outcome values do not make sense in the context of test execution (eg. "not tested" cannot be an outcome of a test run, and also each expectation should not result in "cannot tell").
