### ISSUE TITLE
DIFI: 9.3 Rule Aggregation

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#209]
The paragraph heading should be changed to “Result Aggregation” or “Outcome Aggregation”.

As described in section §8 ACT Data Format (Output Data) a rule will return a list of results, each of which contain 1) the Rule ID, 2) the test subject, 3) the test target, and 4) an outcome. In addition, for the outcome Failed, it must be possible to identify the result for each expectation in a rule. A consistent approach to rule grouping (see feedback to 7 and 8.4), will enrich the data material considerably. Difi has experience with this approach.

**Comment by rdeltour** [comment]
See also #165

**Comment by WilcoFiers** [comment]
Conclusion: Result aggregation is correct. We should add references to "result" and "outcome" as defined in EARL.
