### ISSUE TITLE
Concern about stability of test target pointers

### ISSUE THREAD

**Issue by kasperisager** [w3c/wcag-act#220]
Given [this paragraph of the current spec](https://w3c.github.io/wcag-act/act-rules-format.html#output-test-subject)...

> When a single URL can be used to reference the web page, or other test subject, this URL MUST be used.

...I'm somewhat concerned about the stability of [pointers to test targets](https://w3c.github.io/wcag-act/act-rules-format.html#output-test-target). If we require that a URL be used to identify the test subject, rather than allow tools to embed the test subject in its entirety, we run into the issue that the pointers of a given result set are likely to become invalid, or even incorrect, as the test subject undergoes change. This is especially true for non-expression based pointers.

I'd strongly recommend that the "MUST" be changed to "SHOULD" or even the entire sentence left out. I don't really see a reason as to why we shouldn't simply refer to the [`TestSubject`](https://www.w3.org/TR/EARL/#TestSubject) class defined in EARL.

**Comment by rdeltour** [comment]
I agree., I guess a MAY would even be more appropriate (i.e. it's optional).
