### ISSUE TITLE
Pointers to nodes in (Shadow) DOM

### ISSUE THREAD

**Issue by kasperisager** [w3c/wcag-act#223]
In continuation of #220, I've been thinking quite a bit about how we could go about pointing to nodes in DOM and Shadow DOM without introducing additional pointer types. Embedding a serialisation of DOM (HTML) as Base64 and then using a CSS pointer is entirely possible using EARL, so pointers to DOM nodes are not really an issue. For Shadow DOM, what might be possible to do is embed a serialisation of flattened DOM instead and then again use a simple CSS pointer. I personally really like this approach as it's simple and allows us to embed a document in its entirety, Shadow DOM included.

**Comment by dylanb** [comment]
For security and PII reasons, having this be part of the specification would not be acceptable

**Comment by kasperisager** [comment]
This is not something I'd want included in the spec for the very same reason. It's a question of whether or not we need to extend EARL with additional pointer types in order to accommodate Shadow DOM, which the above would not require as it uses EARL as-is.

**Comment by WilcoFiers** [comment]
I'm going to close this issue as it isn't something this group will be addressing directly.
