### ISSUE TITLE
List of features for exit critiera

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#224]
I went through the document and listed out all the things that we may want to demonstrate. This is a fairly long and complex list, we should discuss where / if / how we can trim this down:

General
  - All rules must conform to the ACT Rules Format

Accessibility requirements
  - At least one atomic rule that has a requirement in WCAG 2
  - At least one composite rule that has a requirement in WCAG 2
  - At least one atomic rule has no accessibility requirement, but is used in a composite rule that has a requirement in WCAG 2
  - At least one rule that has a accessibility requirement that is not part of WCAG

Aspects under test
  - At least two different aspects under tests are used
  - At least two different web content technologies

Applicability
  - At least one applicability is expressed with a formal selector syntax, in addition to a plain language description
  - At least one atomic rule has an applicability different from the composite rule it is used in

Expectations
  - At least one rule with one expectation
  - At least one rule with two expectations
  - At least one rule with more than two expectations

Limitations, Assumptions or Exceptions
  - At least one rules without Limitations, Assumptions or Expectations
  - At least one rule where interpretation is documented in Limitations Assumptions or Expectations

Accessibility Support
  - At least one rule where no accessibility support information was necessary
  - At least one rule where accessibility support information was included

Aggregation
  - At least one implementation that takes results from rules and aggregates it

Changelog
  - At least two rules that include a changelog

Issues list
  - At least two rules that include an issues list

Test cases
  - Every applicability must have at least one inapplicable test case
  - Every expectation must have at least one pass and one fail test case

Implementations and data format
  - At least two fully automated independent implementations of the same ACT rule
    (All test cases that should pass are passing, all test cases that should fail are failing)
  - At least two semi-automated independent implementations of the same ACT rule
    (Some results running against test cases are inconclusive, none of the results contradict the test cases)
  - At least two manual testing methodologies where one of their rules is comparable to an ACT rule

NOT INCLUDED:
  - Benchmarking, expect this to be removed

**Comment by rdeltour** [comment]
* test cases for atomic rules
* accuracy benchmarks for some rules (?)

**Comment by annethyme** [comment]
If it's not already covered by "Implementations", I suggest that we state how many different organisations we want to see implementations from in tools/methodologies.

**Comment by cpandhi** [comment]
+1 to 

- X no. of  rules implementation (atomic and Composed) as per the ACT format

- test cases for the implementation

- Accuracy benchmark with expert review

**Comment by moekraft** [comment]
Ok, I'm thinking like a Project Manager. How about our 50 open issues? We should get them all to a desired state, Closed where possible, Deferred when necessary. We don't want to carry over too much technical debt.

**Comment by Totoronio** [comment]
Besten Dank für Ihre Nachricht.

Ich bin bis am Dienstag, dem 7. August 2018 abwesend und kann Ihre Nachricht erst ab dann wieder bearbeiten. Ihre Email wird nicht weitergeleitet.

Für Anliegen betreffend barrierefreie PDFs wenden Sie sich an andreas.uebelbacher@access-for-all.ch


Beste Grüsse

Anton Bolfing

*******************************************************

Thank you for your message.

I'm out of office until Tuesday, August 7, 2018.  I will not respond to your email until then.

Best regards

Anton Bolfing

**Comment by maryjom** [comment]
I don't think that the non-bulleted items should have a number, as the implementations of various aspects of the spec could be done in a handful of rules or may take many, many more to test implementation of all aspects of the rules format.    It is more important to have the numbers for each feature in the spec that must be tested.  

Also, I plan to review these lists of items to make sure they cover the complete list of features listed in the spec.

**Comment by WilcoFiers** [comment]
Updated the list, see the first post.

**Comment by tbostic32** [comment]
Overall really like the list. I think it really demonstrates a lot you can do with the rules. One thing I could see being removed is for the expectation section just having:

- At least one rule with one expectation
- At least one rule with more than one expectation

I don't think we need to have both a two and more than two.

**Comment by nitedog** [comment]
This looks good! Some thoughts:

- General: this seems superfluous. "at least two" is implied given the remaining requirements listed. I think we only need to say "all rules must conform with the specification" here.
- Technologies: I think we should have most rules addressing HTML, but one or two addressing other technologies (eg. SVG and PDF)
- Test Cases: I think we should have requirements for test cases -- for example, each rule must have at least 2 test cases covering each "pass", "fail", and "inapplicable" situations
- some of the listed bullets are actually conformance requirements, and not needed here (eg. "Applicability must be described objectively, unambiguously and in plain language" or "Expectations of atomic rules must only use information from test aspects, and that rule's applicability and other expectations"

**Comment by annethyme** [comment]
@WilcoFiers: In the section "Implementations of ACT Data Format", does "implementation" also include  outputting results in the ACT Data Format? 
If yes, I suggest we add: 

* At least two fully automated independent implementations of the same ACT rule, _**including expressing the output in a format that has all of the features described in the ACT Data Format**_
(All test cases that should pass are passing, all test cases that should fail are failing)
* At least two semi-automated independent implementations of the same ACT rule, _**including expressing the output in a format that has all of the features described in the ACT Data Format**_
(Some results running against test cases are inconclusive, none of the results contradict the test cases)
* At least two manual testing methodologies where one of their rules is comparable to an ACT rule, _**including expressing the output in a format that has all of the features described in the ACT Data Format**_

**Comment by rdeltour** [comment]
> At least one rules without Limitations, Assumptions or Expectations

s/rules/rule/
s/Expectations/Exceptions/

**Comment by maryjom** [comment]
We are leaving this open until we hear from AG WG on the review of the spec we wish to publish as a CR.
