### ISSUE TITLE
ACT i18n checks

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#226]
For review: Do any of the questions on this page answer to yes:

https://www.w3.org/International/techniques/developing-specs

Please give me a Thumbs up on this topic if you think it doesn't, or leave a comment about what you think does.

**Comment by annethyme** [comment]
If the W3C had considered these things in their templates, I don't think the ACT Rules Format should be impacted by any of this. 
However, some of the definitions might be useful when writing the ACT Rules.

**Comment by maryjom** [comment]
Agree with Anne. Definitions of character and/or string should be added if these terms are used.

**Comment by moekraft** [comment]
We discussed on the ACT TF 7/26 call and have decided that it is important and helpful to add a statement to the specification that rules need to be written in an accessible formatted to support internationalization and globalization. We believe it makes sense to add a statement to Section 4, Rule Structure and to restate statement in Section 15 Rule Quality Assurance. Possibility add a new subsection, 15.3

**Comment by moekraft** [comment]
@nitedog Shadi, do you want to create a first draft of the note/statement? And I will work on a pull request.

**Comment by maryjom** [comment]
The following text was added to the "Rule Structure" section by Wilco to address this issue: 

ACT Rules MUST be written in an format that conforms to the Web Content Accessibility Guidelines [[WCAG]] or a comperable accessibility guidelines recommendation. ACT test cases are allowed to contain inaccessible content. If any test case contains accessibility issues listed in [WCAG 2.1 Section 5.2.5 Non-Interference](https://www.w3.org/TR/WCAG21/#cc5), users MUST be warned of this in advance. Using an accessibility format supports people with disabilities. It also makes internationalisation of ACT rules easier.

@moekraft However, I notice there's a typo - "comperable" should be "comparable", and I thought we're supposed to be using U.S. English spelling of "internationalization" vs. UK English spelling "internationalisation".

**Comment by nitedog** [comment]
I agree with @maryjom on her edit suggestions. In addition, I'm not sure I agree with the last sentence. I suggest changing these two last sentences:

> Using an accessibility format supports people with disabilities. It also makes internationalisation of ACT rules easier.

To this instead:

> ACT Rules MUST also follow [internationalization authoring practices](https://www.w3.org/International/techniques/authoring-html)

Having said that, we may have to change the "MUST" to a "SHOULD" (or even less) because the reference is not a normative specification.
