### ISSUE TITLE
Having a common rule format is not sufficient to ensure consistent interpretation and application of accessibility requirements.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag-act#228]
In the Introduction, it is asserted that "this format is intended to enable a consistent interpretation of how to test for accessibility requirements and promote consistent results of accessibility tests".

However, having a common format for the expression of testing rules is not sufficient to achieve these objectives. The rules themselves, in the format defined in this document, are expressed in natural language, and may or may not be amenable to the implementation of a deterministic testing algorithm. Like the underlying Success Criteria, some rules are expected to require careful judgment to apply appropriately. Whether different human evaluators, on different occasions, are likely to achieve consistent and hence reliable results by applying a body of testing rules depends largely on how the rules are formulated and expressed. The rule format doesn't address this problem; it merely shifts the problem from that of interpreting and applying Success Criteria, to that of interpreting and applying testing rules. The testing rules may be vague, or may introduce interpretive problems of their own, just as Success Criteria do.

Having a common rule format may be useful in documenting testing rules, but it doesn't solve problems of inter-rater reliability associated with accessibility guidance.

What is needed, it seems to me, in addition to any common rule format, is an empirical method of evaluating the inter-rater reliability of proposed testing rules and for demonstrating that different evaluators converge not only on the same evaluations, but on what are reasonably considered correct evaluations.

To build a high-quality body of testing rules, I think such an empirical method is necessary. Developing such a method lies outside the scope of this document.

It seems to me that the scope of the document should be clarified with respect to the foregoing issues. The statement quoted above, from the Introduction, seems misleading as it stands, in that it can readily be interpreted as claiming that the common rule format solves more of the problem than it actually can or does.

**Comment by WilcoFiers** [comment]
Proposal to update the term from:

> this format is intended to enable a consistent interpretation of how to test for accessibility requirements and promote consistent results of accessibility tests"

To something like this:

> this format is intended to enable **greater consistency in interpretation** of how to test for accessibility requirements and promote consistent results of accessibility tests"

**Comment by maryjom** [comment]
@WilcoFiers @jasonjgw Shadi suggested edits to the introduction section that overlaps with this particular comment. Please check [PR# 265](https://github.com/w3c/wcag-act/pull/265) to ensure the updates address the issue.

**Comment by maryjom** [comment]
This issue duplicates #245

**Comment by WilcoFiers** [comment]
This issue should be resolved with the updated introduction.
