### ISSUE TITLE
3. ACT Rule Types - Clarify example

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#230]
The example "Header cells in HTML tables" states: 
"If any one of these rules passes, the table cell can pass the composed rule."

The wording "**can** pass the rule" is unclear.
If there are any additional situations, in which the rule is not passed although all the atomic rules are passed, then this should be stated explicitly. Otherwise the sentence should be changed to: "If any one of these rules passes, the table cell passes the composed rule."

**Comment by WilcoFiers** [comment]
"test result is a pass"
