### ISSUE TITLE
7. Accessibility Requirements - Improvement suggestion

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#231]
Change "... from different sources, such as local laws, internal standards, etc. "
to "... from different sources, such as **national or** local laws, internal standards, etc."

Accessibility legislation is usally on national or state level. Local laws are not that common.

**Comment by maryjom** [comment]
This looks like a reasonable editorial change to me.

**Comment by WilcoFiers** [comment]
Proposal: Take out "Local" just say "laws"

**Comment by maryjom** [comment]
Once we merge the pull request this can be closed.

**Comment by moekraft** [comment]
Closed by PR #273 and #276.
