### ISSUE TITLE
8.1. Common Aspects - Question

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#233]
How will the ACT rules format accommodate rules for the new Success Criteria of WCAG 2.1 (Orientation, Gestures, etc.)? Is there a common way to describe those?

**Comment by WilcoFiers** [comment]
Suggestion to maintain a list of common aspects separate from the spec and only provide examples in the spec itself.

**Comment by annethyme** [comment]
Created https://github.com/w3c/wcag-act/pull/242 as a suggested solution.

**Comment by WilcoFiers** [comment]
@annika-FTB The answer to the question is yes, ACT Rules are not limited to WCAG 2.0. Auto-WCAG is currently working on a few WCAG 2.1 rules. The first one of these is already published here:

https://auto-wcag.github.io/auto-wcag/rules/SC1-3-5-autocomplete-valid.html

**Comment by maryjom** [comment]
Reopened this issue, as we haven't yet surveyed the suggested updates and are doing that this week.

**Comment by moekraft** [comment]
Merged PR #242
