### ISSUE TITLE
15.2. Accuracy Benchmarking - Update definition

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#236]
Your definition of accuracy is not aligned with the definition used in statistics / information science. In general, higher accuracy means that an approach is better. In your definition a higher number means that the approach performed worse!

See [Wikipedia - Accuracy and precision:](https://en.wikipedia.org/wiki/Accuracy_and_precision#In_binary_classification)
"Accuracy is the proportion of true results (both true positives and true negatives) among the total number of cases examined."

Another useful approach might be to consider **precision and recall** as indicators in the benchmarking.
See [Wikipedia - Precision and recall:](https://en.wikipedia.org/wiki/Precision_and_recall)
"Precision is the fraction of relevant instances among the retrieved instances, while recall is the fraction of relevant instances that have been retrieved over the total amount of relevant instances."

**Comment by WilcoFiers** [comment]
Should be addressed along side #239

**Comment by WilcoFiers** [comment]
Propose to remove accuracy and make descriptions of false positives / false negatives non-normative.

**Comment by maryjom** [comment]
Can close once #277 is merged.
