### ISSUE TITLE
16. Rule Aggregation - Improve example

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#237]
This section talks about "aggregation" of results for the same rule that has been applied to several test targets within the same web page (test subject). This is **not** the same type of aggregation as used in the composed rules. 

It should be made clear that these are different types of aggregation. Maybe use another name for one of them(?)

Moreover the example is section 16 adds to the confusion since it mixes both types of aggregation (several rules and several test targets).

**Comment by WilcoFiers** [comment]
Suggestion to use a different term for composed rules. TBD

**Comment by maryjom** [comment]
Link to the section: [output aggregation](https://www.w3.org/TR/act-rules-format/#output-aggregation)
We should split the example into 3 parts:
1. aggregation of the results from multiple rules.
2. aggregation of results for multiple occurrences on a page
3. More complex when you have aggregation over both the above types.
