### ISSUE TITLE
Structure of the text

### ISSUE THREAD

**Issue by annika-FTB** [w3c/wcag-act#238]
The descriptions of the two types of rules are mixed up in several places. 

E.g. the headings of Sections 8 and 9 read "Atomic rules only" but the subsequent text also covers composed rules.

Suggestion: Restructure the document so that all the information about atomic rules (and composed rules resp.) can be found in one place.

**Comment by WilcoFiers** [comment]
Discussed in the meeting to put a single sentence paragraph for each section that's only for one type of rule to make it explicit it does not apply to the other rule type.

**Comment by moekraft** [comment]
From Shadi: 
Mixing of must and optional is confusing. Also the mixing of atomic and composed. Better to split up in:
-	 Atomic MUST
-	 Atomic MAY
-	 Composed MUST
-	 Composed May
Or in:
-	 MUST atomic & composed
-	 MAY atomic & composed
[Accessibility Conformance Testing.docx](https://github.com/w3c/wcag-act/files/2293703/Accessibility.Conformance.Testing.docx)

**Comment by WilcoFiers** [comment]
The structure has been significantly revised. I think this is a good improvement. IMO, this issue is resolved.
