### ISSUE TITLE
Abstract: Editorial updates (Shadi)

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#244]
The Accessibility Conformance Testing (ACT) Rules Format 1.0 defines a format for writing accessibility test rules. These rules can be carried out fully-automatically, semi-automatically, and manually. This common format allows developers of accessibility testing tools and methodologies to document and share their test procedures. This enables transparency and reliance of the testing methods, which also promotes common understanding and harmonization of the accessibility requirements.
[Accessibility Conformance Testing.docx](https://github.com/w3c/wcag-act/files/2293582/Accessibility.Conformance.Testing.docx)

**Comment by WilcoFiers** [comment]
PR merged, closing this issue. Due to time constraints I'm merging all of the editorials changes for a single vote.
