### ISSUE TITLE
Introduction: Editorial updates (Shadi)

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#245]
There are currently many testing tools and methodologies available, which aid their users in testing the conformance of web content to accessibility standards, such as the Web Content Accessibility Guidelines (WCAG) [WCAG]. As the Web continues to grow in both size and complexity, these tools and methodologies are essential for managing the accessibility of content available on the Web.
This specification, Accessibility Conformance Testing (ACT) Rules Format, enables consistent documentation of accessibility test procedures. In turn, it allows common interpretation of how to test for accessibility requirements, and promotes consistent results of accessibility tests. It is used to describe both manual accessibility test procedures as well as automated and semi-automated test procedures performed by accessibility testing tools.
[Accessibility Conformance Testing.docx](https://github.com/w3c/wcag-act/files/2293646/Accessibility.Conformance.Testing.docx)

**Comment by WilcoFiers** [comment]
PR merged, closing this issue. Due to time constraints I'm merging all of the editorials changes for a single vote.
