### ISSUE TITLE
Rule Identifier: Example needed (Shadi)

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#248]
5. Rule Identifier
An ACT Rule MUST have a unique identifier that can be any unique text value, such as plain text, URL or a database identifier.

"Example would be helpful here" - Shadi
[Accessibility Conformance Testing.docx](https://github.com/w3c/wcag-act/files/2293723/Accessibility.Conformance.Testing.docx)

**Comment by maryjom** [comment]
Is there a good example we can pull from a rule developed by the AUTO-WCAG CG?

**Comment by WilcoFiers** [comment]
We need to decide what kind of IDs we want. Something like what auto-WCAG has been doing: `SC1-2-3-some-description` or something like what the techniques have: `ACT123`

**Comment by WilcoFiers** [comment]
Should use the auto-wcag format as an example.

**Comment by WilcoFiers** [comment]
Closed by #283
