### ISSUE TITLE
Rule Description: Example needed (Shadi)

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#249]
6. Rule Description
An ACT Rule MUST have a description that is in plain language and provides a brief explanation of what the rule does.

"Example would be helpful here." - Shadi
[Accessibility Conformance Testing.docx](https://github.com/w3c/wcag-act/files/2293728/Accessibility.Conformance.Testing.docx)

**Comment by maryjom** [comment]
Can we pull an example from a well written test case developed by the AUTO-WCAG CG?  If so, which is in the best shape to use?
