### ISSUE TITLE
Clarify definition of Aspect under Test needed

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#264]
During weekly WCAG ACT TF meeting, an issue was raised regarding what is meant by Aspect under test.

**Comment by annethyme** [comment]
Romain had a point last time that "with no overlap between the aspects" in "Each aspect MUST be discrete with no overlap between the aspects" does not really make sense. 

@skotkjerra, @kasperisager and I have discussed and agree with this point. 

We suggest deleting "with no overlap between the aspects".

**Comment by annethyme** [comment]
Editorial comment: 

In the section that currently looks like this: 

> [=Atomic rules=] MUST list the aspects used in the [applicability](#applicability-atomic) and [expectations](#expectations-atomic). Some rules may need to operate on several aspects simultaneously, such as both the HTTP messages and the DOM tree. There SHOULD NOT be an aspects under test list for composite rules.
> 
> An atomic rule MUST include a description of all the aspects under test by the rule. Each aspect MUST be discrete with no overlap between the aspects. Some aspects are already well defined within the context of web content, such as HTTP messages, DOM tree, and CSS styling [[CSS2]], and do not warrant a detailed description. Other aspects may not be well defined or even specific to web content. In these cases, an ACT Rule SHOULD include either a detailed description of the aspect in question or a reference to that description.
> 

We suggest moving the requirement for composite rules all the way to the end, to make the requirements for atomic rules less broken up: 

> [=Atomic rules=] MUST list the aspects used in the [applicability](#applicability-atomic) and [expectations](#expectations-atomic). Some rules may need to operate on several aspects simultaneously, such as both the HTTP messages and the DOM tree. 
> 
> An atomic rule MUST include a description of all the aspects under test by the rule. Each aspect MUST be discrete with no overlap between the aspects. Some aspects are already well defined within the context of web content, such as HTTP messages, DOM tree, and CSS styling [[CSS2]], and do not warrant a detailed description. Other aspects may not be well defined or even specific to web content. In these cases, an ACT Rule SHOULD include either a detailed description of the aspect in question or a reference to that description.
> 
> There SHOULD NOT be an aspects under test list for composite rules.

**Comment by nitedog** [comment]
I like the editorial suggestion from @annethyme above. I had suggested something similar in [the previous survey](https://www.w3.org/2002/09/wbs/93339/ACT27AUG2018/results).

As to the actual technical concern raised by @rdeltour, is "overlap" the issue versus the definition itself (eg. "discrete")? Not sure that removing "with no overlap between the aspects" will solve the issue, as the definition still seems to raise concerns.

**Comment by rdeltour** [comment]
> As to the actual technical concern raised by @rdeltour, is "overlap" the issue versus the definition itself (eg. "discrete")? Not sure that removing "with no overlap between the aspects" will solve the issue, as the definition still seems to raise concerns.

I'm OK with having a rather lose definition, since it will be very difficult to get a precise one.
My concern is with the whole sentence "Each aspect MUST be discrete with no overlap between the aspects", which I believe can't be unambiguously interpreted or verified, so can't be a normative conformance requirement. I would just remove the whole sentence.

As for the definition, a potential issue is that we define the _aspect_ by referring to _test subject_, but we don't actually have a definition for this. The term currently points to the related output data format section (14.1), which doesn't include a definition (it only describes the requirement to identify the subject with a URL in the output).

**Comment by WilcoFiers** [comment]
Discussed on the call, will remove the problematic sentence.

**Comment by moekraft** [comment]
I have entered PR #274 to reflect Anne and Shadi's feedback and  the feedback from the 9/20 meeting. Please review, https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/w3c/wcag-act/b01af906514def95d00cdad1bc1d16cbe34d7add/act-rules-format.bs#input-aspects
