### ISSUE TITLE
Test subject is inconsistent with EARL language

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#275]
Test subject, the way it is used in ACT RF is different from how it is used in EARL. In EARL, a test subject is some "thing" that has been tested. That include test targets. The way to understand this is that EARL test subject is anything that has a result. In ACT RF, that includes test target, as well as the web page that is tested.

To solve this I think we should rename "test subject" to "test page". That simply have two types of test subjects: Test pages and Test targets.

**Comment by nitedog** [comment]
What does it mean "anything that has a result"?

**Comment by annethyme** [comment]
Without too much knowledge of EARL, my concern is using the term "page" that is not well defined. What if the same page has different states - how would that work with a "test page" definition?

**Comment by kasperisager** [comment]
I personally disagree with using the term "test page". The term "test subject" as defined by EARL seems perfectly fit for what ACT RF is using it for; the thing being tested against some criterion, i.e. the aspects under test. The example provided in EARL speaks for this as well:

```xml
<earl:TestSubject rdf:about="http://www.example.org/">
  <dct:title xml:lang="en">example.org Web site</dct:title> 
  <dct:description xml:lang="en">Each page on the example.org Web site</dct:description> 
  <dct:hasPart rdf:resource="http://www.example.org/style.css"/> 
  <dct:hasPart rdf:resource="http://www.example.org/page1.html"/> 
  <dct:hasPart rdf:resource="http://www.example.org/page2.html"/> 
  <dct:hasPart rdf:resource="http://www.example.org/image1.png"/> 
  <dct:hasPart rdf:resource="http://www.example.org/image2.png"/> 
</earl:TestSubject>
```

The other and perhaps more fundamental issue with using the term "page" is that we limit the framework to describe only rules that test whatever fits the definition of a "page". What about rules that test content that do not fit this term, such as an SVG, an EPUB, or even a stylesheet? I don't think it would be appropriate to talk about those as "pages". [Alfa](https://github.com/Siteimprove/alfa), for example, uses the term "document" internally, which applies universally to anything published on the world wide web.

**Comment by WilcoFiers** [comment]
As per last week's discussion, the conclusion was that my interpretation was incorrect and the Rules Format is consistent with EARL. Closing the issue.
