### ISSUE TITLE
"ACT Rules" or "ACT rules"? 

### ISSUE THREAD

**Issue by annethyme** [w3c/wcag-act#278]
Do we write ACT Rules or ACT rules? Both is used in the spec, and I am not sure if it is according to a pattern.

**Comment by nitedog** [comment]
I think we should consistently use "ACT Rules" to denote these types of rules that conform to the ACT Rules Format specification. The term "rules" (without "ACT" in front) can be used as the generic term for any type of rule.

**Comment by moekraft** [comment]
Addressed by PR #303
