### ISSUE TITLE
Normative or Informative

### ISSUE THREAD

**Issue by goodwitch** [w3c/wcag-act#282]
Dear ACT,

As you are building the data structure for rules, can you add an indicator that clearly defines if a rule is based on normative (required for compliance) or informative? 

This will be very useful for making sure that a person shooting for minimum compliance can clearly understand if they need to meet a rule (or if the rule is just one way to meet a requirement).

**Comment by annethyme** [comment]
@goodwitch, I was just discussing with a colleague how to understand your comment here. 
As we read it, you suggest adding something like this: 

"Image has accessible name" rule
- normative for 1.1.1 Non-Text Content

"Skip to content link" rule
- informative for 2.4.1 Bypass Blocks

Is that correctly understood?

**Comment by goodwitch** [comment]
Yes!  That is exactly what I meant!

**Comment by WilcoFiers** [comment]
The group has taken a long hard look at this issue and we think we've resolved this. Rules now MUST indicate whether or not they are required for conformance to the accessibility requirements document which it was designed to test. Thank you for submitting the issue @goodwitch!
