### ISSUE TITLE
Proposal to (slightly) rearange the spec outline

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#284]
TL;DR: Can we consider grouping back the sections describing ACT Rules content together? 

I know we've been back and forth about this, and it's quite late in the process, but as I review the draft proposed to be sent to CR I find the current flat outline to be very slightly difficult to navigate.

I'm proposing:
- moving section 5 to 13 (from "Rule Identifier" to "Accessibility Support") under section 4 ("ACT Rule Structure")
- renaming "ACT Rule Structure" to "ACT Rule Content"

**Comment by moekraft** [comment]
@rdeltour Hi Romain, I just want to confirm the updates requested. Are you asking that Rule Identifier move it's location to after Accessibility Support? 
Descriptive Title
~~Rule Identifier~~
Rule Description
Rule type
Accessibility Requirements
Aspects Under Test (for atomic rules) OR Atomic Rules List (for composite rules)
Applicability
Expectations
Assumptions
Accessibility Support
**Rule Identifier** <==Move here?
Test Cases
Change Log
Issues List
Acknowledgements (optional)
Background (optional)
ACT Rules Format outcome definition

**Comment by rdeltour** [comment]
No, I was meaning to the rule-structure sections one level down:

1. Introduction
1. Scope
1. ACT Rule Types
1. ACT Rule Structure
    1. Rule Identifier
    1. Rule Description
    1. Accessibility Requirements
    1. Aspects Under Test (Atomic rules only)
    1. Atomic Rules List (Composite rules only)
    1. Applicability
    1. Expectations
    1. Assumptions
    1. Accessibility Support
    1. Test Cases
    1. Change Log
    1. Issues List (optional)
    1. Acknowledgements (optional)
    1. Background (optional)
1. Rule Accuracy
1. Harmonization
1. Definitions

instead of the current flat structure:

1. Introduction
1. Scope
1. ACT Rule Types
1. ACT Rule Structure
1. Rule Identifier
1. Rule Description
1. Accessibility Requirements
1. Aspects Under Test (Atomic rules only)
1. Atomic Rules List (Composite rules only)
1. Applicability
1. Expectations
1. Assumptions
1. Accessibility Support
1. Test Cases
1. Change Log
1. Issues List (optional)
1. Acknowledgements (optional)
1. Background (optional)
1. Rule Accuracy
1. Harmonization
1. Definitions

**Comment by moekraft** [comment]
Got it. And also renaming to Rule Content

**Comment by moekraft** [comment]
Waiting for current PRs to merge before tackling since hitting merge conflicts in current PRs.

**Comment by WilcoFiers** [comment]
This has been done.
