### ISSUE TITLE
Create introduction to "What is an ACT rule?" in the spec

### ISSUE THREAD

**Issue by annethyme** [w3c/wcag-act#292]
Per break-out session at TPAC on [Spec Editing Best Practices](https://lists.w3.org/Archives/Public/spec-prod/2018OctDec/0011.html), Wilco and Anne realised that there is currently nothing in the ACT Rules Format that introduces briefly/overall to "What is an ACT Rule" before we dive into the specifics of rule types and structure. 

We should have an introduction like this in the ACT Rules Format.

**Comment by maryjom** [comment]
See pull request #310

**Comment by maryjom** [comment]
This is done and approved.
