### ISSUE TITLE
Clarify that test subjects have only one outcome

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#299]
Some questions were raised about how to express the results of an ACT Rule using EARL. This lead to the conclusion that it is not immediately obvious that a rule can only have one outcome for a given test subject. This should be cleared up.

**Comment by kasperisager** [comment]
This very much seems to contradict the following example provided by EARL:

```rdf
<earl:Assertion rdf:ID="ass1">
  <earl:result rdf:resource="#error1" />
  <earl:test rdf:resource="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" />
  <earl:subject rdf:resource="http://example.org/resource/index.html" />
  <earl:assertedBy rdf:resource="#assertor01" />
</earl:Assertion>

<earl:Assertion rdf:ID="ass2">
  <earl:result rdf:resource="#error2" />
  <earl:test rdf:resource="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" />
  <earl:subject rdf:resource="http://example.org/resource/index.html" />
  <earl:assertedBy rdf:resource="#assertor01" />
</earl:Assertion>

<earl:Assertion rdf:ID="ass3">
  <earl:result rdf:resource="#error3" />
  <earl:test rdf:resource="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" />
  <earl:subject rdf:resource="http://example.org/resource/index.html" />
  <earl:assertedBy rdf:resource="#assertor01" />
</earl:Assertion>
```

Source: https://www.w3.org/TR/EARL10-Guide/#report-assert

In the above, the same test (`http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd`) has a total of 3 errors for a given test subject (http://example.org/resource/index.html) resulting in 3 separate assertions with 3 separate results and outcomes.

The way I read the EARL schema, each individual result for a given test will result in a single assertion for the test subject. If you therefore wish to know the outcome of a test across all its resulting assertions, you have to aggregate.
