### ISSUE TITLE
replace "failure condition"

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-act#327]
From Alistair Garrison [via email](https://lists.w3.org/Archives/Public/public-wcag-act/2019Jan/0017.html):

> The Atomic Rule definition (copied below for ease) is:
> 
> Atomic rules describe how to test a specific type of solution. It contains a precise definition of what elements, nodes or other "parts" of a test subject are to be tested, and when the test subject is considered to fail the rule. These rules are to be kept small and atomic. This means that atomic rules test a single "failure condition", and do so without using the findings from other rules.
> 
> The issue is – atomic rules test a single “failure condition”.  This should be changed to – atomic rules test a “single expected outcome”…
> 
> Why? If we look at all examples rules we see they all describe positive expected outcomes; definitely not “failure conditions” e.g.
> 
> 1. Video elements have a transcript
> 2. Video elements have an audio description
> 3. Video elements have a description track
> 4. This rule checks that the HTML page has a title
> 5. Etc…
> 
> Yes, a late stage find – but, something which other reviewers would pull up.

**Comment by nitedog** [comment]
How about we simply remove "failure", so that the sentence says:

> This means that atomic rules test a single condition ...

**Comment by skotkjerra** [comment]
That solves it without introducing further complications.
