### ISSUE TITLE
Generate content for Section 6.1 Output Data

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#33]

**Comment by WilcoFiers** [comment]
I've created a PR for first review:
https://github.com/w3c/wcag-act/pull/41

**Comment by maryjom** [comment]
The content was added in pull request #41 and reviewed in the [18 January survey](https://www.w3.org/2002/09/wbs/93339/ACTTF18Jan2017/results#xQ3) which had only editorial comments.
