### ISSUE TITLE
Update the CSS reference in the Common Input Aspects note

### ISSUE THREAD

**Issue by rdeltour** [w3c/wcag-act#333]
Shouldn't `[css-2018]` be referenced instead of `[CSS2]`?

**Comment by rdeltour** [comment]
It seems the latest Snapshot note can be referenced via the canonical link  https://www.w3.org/TR/css/

**Comment by nitedog** [comment]
This seems addressed but PR not referenced.

**Comment by moekraft** [comment]
Updated references to CSS to link to  https://www.w3.org/TR/css/. Note: due to a bikeshed issue, need to use detailed link text, [CSS Styling] or [Cascading Style Sheets] while [CSS]( https://www.w3.org/TR/css/) causes an error in Bikeshed.
