### ISSUE TITLE
Generate initial content for Rule Aggregation, section 6.2

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#34]
Assigned to Alistair

**Comment by WilcoFiers** [comment]
As per Alistair's request, I drafted a section for this. I've created a PR, which can be found here:
https://github.com/w3c/wcag-act/pull/46

**Comment by maryjom** [comment]
Reviewed in the [8 February survey](https://www.w3.org/2002/09/wbs/93339/ACTTF8Feb2017/results#xQ6).  Review results were incorporated into pull request #46.
