### ISSUE TITLE
Under Acknowledgements mention "Community Group for incubation"?

### ISSUE THREAD

**Issue by annethyme** [w3c/wcag-act#340]
If ACT rules after incubation in e.g. Community Groups are collected in a common repository, it would be useful to know where the rule was originally incubated. 
We could mention this as a possible item under "Acknowledgements".

**Comment by WilcoFiers** [comment]
@nitedog would you say this is editorial? It seems like adding another "may", but I'm not sure how to draw that line.

**Comment by nitedog** [comment]
I think this is for the rules/repository and not for the spec itself?

**Comment by WilcoFiers** [comment]
Discussed on the TF to add ACT-Rules CG in the acknowledgements, group thinks this is a good suggestion.

**Comment by WilcoFiers** [comment]
This issue was addressed here: https://github.com/w3c/wcag-act-rules/pull/19/files
