### ISSUE TITLE
"test aspects" confusing

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag-act#341]
In https://w3c.github.io/wcag-act/act-rules-format.html#input-aspects there is example 7 and example 8 - it is a bit unclear if the word test is used as a noun or a verb. I think it is a noun "test aspects" but to align with the section heading perhaps these should say "Input aspects"?

**Comment by WilcoFiers** [comment]
Good point. I'm just going to make those changes. This was a hold-over from when we called these things test aspects. Good catch.
