### ISSUE TITLE
Issue with Example 11

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag-act#342]
Example 11 reads:
Example: A rule for labels of HTML input elements might have the following expectations:

- Each test target has an accessible name (as described in Accessible Name and Description: Computation and API Mappings 1.1). [accname-aam-1.1]
- The accessible name describes the purpose of each test target.

It might help to replace "test target" with what the test target actually is in the bulleted items, e.g. "each HTML input element"

This example also makes it seem that the label is the target, but the details make it seem that the inout it. Could be clarified?

**Comment by WilcoFiers** [comment]
I like the suggestion. We never properly discussed it, but I had the impression Shadi prefers the use of "test target".

**Comment by nitedog** [comment]
No - no preferences on this one (for a change ;-) )

**Comment by moekraft** [comment]
Note: Target is the input element not the label.
