### ISSUE TITLE
Generate initial content 7.1 Managing Exceptions (assigned to Charu)

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#35]
Assigned to Charu.

**Comment by moekraft** [comment]
Assigning Charu. She is now a member of W3C. Note: Invite hidden on github.com/w3c page.

**Comment by maryjom** [comment]
Thanks for helping Charu with that. Now we need to get Alistair and Alan
Smith on board.


Best regards,


Mary Jo
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                    Mary Jo                                                                    
                    Mueller                                                                    
                    Accessibility                                                              
                    Standards                                                                  
                    Program                                                                    
                    Manager                                                                    
                    IBM                                                                        
                    Accessibility,                                                             
                    IBM Research,                                                              
                    Austin, TX                                                                 
                    Phone:                                                                     
                    512-286-9698 |                                                             
                    Tie-line:                                                                  
                    363-9698                                                                   
                    Search for                                                                 
                    accessibility                                                              
                    answers                                                                    
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               



"If your actions inspire others to dream more, learn more, do more and
become more, you are a leader."
~John Quincy Adams



From:	"Maureen (Moe) Kraft" <notifications@github.com>
To:	w3c/wcag-act <wcag-act@noreply.github.com>
Cc:	Subscribed <subscribed@noreply.github.com>
Date:	01/09/2017 11:41 AM
Subject:	Re: [w3c/wcag-act] Generate initial content 7.1 Managing
            Exceptions (assigned to Charu) (#35)



Assigning Charu. She is now a member of W3C. Note: Invite hidden on
github.com/w3c page.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
