### ISSUE TITLE
Editorial updates

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#356]
Section 4.5.1. Input Aspects (Atomic rules only)
- input for atomic rule > input for the atomic rule

Section 4.9. Accessibility Support, Example 17
- used satisfy > used to satisfy

Section 5. Rule Accuracy, last paragraph
- mean > means

Appendix 1
- Example 2 does not have a description

Appendix 4, Criteria C5
- a accessibility > an accessibility

**Comment by maryjom** [comment]
Proposed response:

Thank you for your review of the ACT Rules Format spec. We have made all of the editorial changes you suggested - good catches!  Please review the new version of the spec **_(add in link when it is available)_** and let us know within 48 hours whether this satisfies the issue you raised.
