### ISSUE TITLE
Optional items under MUST keyword

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#357]
On section "4. ACT Rule Structure" the list of MUST have items of an ACT rules includes optional items. Shouldn't the optional items be under a MAY keyword?

**Comment by tbostic32** [comment]
The below seems like a relatively simple and easy fix.

An ACT Rule MUST consist of at least the following items:

- Descriptive Title
- Rule Identifier
- Rule Description
- Rule Type
- Accessibility Requirements Mapping
- Rule Input, which is one of the following:
       - Input Aspects (for atomic rules) OR
       - Input Rules (for composite rules)
- Applicability
- Expectations
- Assumptions
- Accessibility Support
- Test Cases
- Change Log
- Glossary

An ACT Rule MAY also contain:
- Issues List
- Background
- Acknowledgements

**Comment by maryjom** [comment]
@WilcoFiers @nitedog I wasn't sure I can add the "MAY" as that is normative language and we are in CR.  Didn't know if that would cause problems, so I instead added "can"...or I could use "might" if you prefer.

**Comment by nitedog** [comment]
I think is not changing the meaning of what we had before, it is just making it explicit (ie. we had an implicit MAY there all the time, so this can probably be considered as an editorial change).

**Comment by maryjom** [comment]
OK, changed it to "MAY".

**Comment by maryjom** [comment]
Proposed response to this issue (for ACT TF review): 

Thank you for your review and comments on the ACT Rules Format spec. I have made the changes to separate out the optional portions of the rules with the exact text you suggested. Let us know if this resolves the issue you raised.  Once the task force approves the change on 27 June, it will be merged and incorporated into the next version.
