### ISSUE TITLE
"Unique identifier" scope 

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#358]
The scope of the unique identifier is not defined. Does it have to be universally unique? If so, how is that ensured?

**Comment by WilcoFiers** [comment]
Task: Come up with a definition of "unique identifier".

**Comment by maryjom** [comment]
@WilcoFiers See discussion from the 30 May teleconference.

**Comment by WilcoFiers** [comment]
@carlosapaduarte thank you for the feedback. The ACT Task Force has decided to add a brief inline definition. The identifier is meant to be unique for within a ruleset. It is not necessary to have an identifier that is globally unique.
