### ISSUE TITLE
Expectations for Composite Rules

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#359]
The text of section "4.7.2. Expectations for Composite Rules" hints that composite rules can have more than one expectation ("All expectations of a composite rule"). To express the logic of a composite rule a single expectation is enough. This should be clarified. Editing the text to "The expectation of a composite rule" should be enough.

**Comment by maryjom** [comment]
@WilcoFiers See meeting minutes from 30 May where you said you'd reach out to Carlos.

**Comment by WilcoFiers** [comment]
@carlosapaduarte Thank you for the feedback. The ACT Task Force has looked at your suggestion and is of the opinion that limiting composite rules to a single expectation, while allowing multiple expectations for atomic rules is not a meaningful change.

By using "and", two expectations can always be expressed as a single expectation. Using multiple expectations is a way to break up the logic of a rule, making it easier to consume and reason about.

I hope this sufficiently answers your question. Let me know if you have any further concerns.
