### ISSUE TITLE
Rule's date and version number

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#360]
The Change Log states that "Each new release of an ACT Rule MUST be identifiable with either a date or a version number". It is not clear where the date and the version number should be placed (there are no fields for these in the rule structure).

**Comment by WilcoFiers** [comment]
Talked about it in TF. We're going to include this in the identifier section to make it more prominent.

**Comment by maryjom** [comment]
@WilcoFiers See discussion from 30 May meeting.

**Comment by WilcoFiers** [comment]
@carlosapaduarte The ACT Task Force has decided to move the part about version identification from the Change Log section into the Rule Identifier section, as it seemed a more appropriate section heading to put the requirement under.
