### ISSUE TITLE
Reference to specific vendor

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#361]
An example in the definition of "Test Subject" makes reference to "A Vue component file". Do you want to keep a reference to a specific vendor technology?

**Comment by WilcoFiers** [comment]
"Vue component" -> "Web component"

**Comment by WilcoFiers** [comment]
@carlosapaduarte Thank you for reporting. The ACT Task Force has looked at the comment and decided to change "Vue component" to "web component" to be framework neutral.
