### ISSUE TITLE
Examples 3 and 4 in Appendix 1 are identical

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#362]
Even if they are exemplifying different aspects, being the same example could lead readers to wonder if there was a mistake.

**Comment by WilcoFiers** [comment]
Shadi will be updating an example.

**Comment by nitedog** [comment]
**Proposed response**

Thank you for your comment. We believe Pull Request #377 addresses your concern, please let us know if you do not agree to how it was resolved.
