### ISSUE TITLE
Feedback Lisa Louise Davis

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#363]
I reviewed the document this morning. Overall, it seems thorough and understandable. I did find the Rule input section a little obscure, but with careful reading and a quick look at Common Input Aspects, I think I figured it out.

**Comment by maryjom** [comment]
@WilcoFiers I've drafted the following response to be sent to Lisa Louise Davis. I'm assuming you have her email address so we can send an email once the TF agrees on the response and resolution.

Proposed response to her:

Thank you for your comment on the ACT Rules Format. The ACT TF has taken into consideration the confusion you expressed in understanding the Rule Input section of a rule and what the expected content would be for that field.  We have made some changes intended to address your concern and make things more clear. 

Please review the section again in the latest draft (with a link to it). Let us know if this resolves the issue or if they do not resolve your concern. Please respond within 48 hours.
