### ISSUE TITLE
Intention to submit feedback and implementation report

### ISSUE THREAD

**Issue by cptvitamin** [w3c/wcag-act#365]
Cyxtera intends to provide feedback and an implementation report for the Accessibility Conformance Testing Rules Format 1.0.  However, as a new member to the AGWG and ACT-Rules TF, we regret that we will not be able to submit this work by May 28, 2019.  We do expect to be able to submit both feedback and an implementation report by June 11, 2019.  Our hope is that this contribution will still be useful as ACT-Rules makes progress towards 1.0.

**Comment by nitedog** [comment]
@cptvitamin what is the status of this?
