### ISSUE TITLE
Level Access Feedback: General

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#366]
**Suggestion**: We need to tighten the outcome data format – possibly restricting it to one form.  The examples suggested for data-format are not trimmed to only those pieces of the format which are 100% necessary.  For example, we likely need the id of the coded test being run, the testing engine name + version, the id of the rule being claimed as supported, the id of the unit test and the outcome from the coded test.

**Reason**: People are already starting to implement tools which read this outcome format.  It would be best to promote a single format ASAP, which of course could be a cut-down form of EARL.   You’ll notice, that both Alfa and aXe already report using different structural versions of EARL (and, Deque’s earl context seems different to the earl-act.json context) – with differences in the additional information presented too.  Without clarity more variants from more tool developers will follow.

**Comment by WilcoFiers** [comment]
@nitedog will add another example to the Appendix.

**Comment by nitedog** [comment]
**Proposed response**

Many thanks for your comment. As discussed during the [ACT TF teleconference call on 27 June 2019](https://www.w3.org/2019/06/27-wcag-act-minutes.html#item11), we believe Pull Request #389 addresses your concern. It provides clearer examples, includes the JSON context, and links out to further resources on EARL and JSON-LD. Please let us know if you disagree with how this was resolved.

**Comment by aglevelaccess** [comment]
Proposed response acceptable.
