### ISSUE TITLE
Level Access Feedback: Rule Input

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#369]
**Suggestion**: We might consider extending the list under each example to include “ECMAScript” and “Shadow DOM”.

**Reason**: Both must now be assumed to be present as default when testing

**Comment by kasperisager** [comment]
Shadow DOM is already included within the DOM input aspect given that Shadow DOM is defined in DOM: https://dom.spec.whatwg.org/#shadowroot.

As for ECMAScript (JavaScript), this would only be relevant in cases where JavaScript alone is the aspect being tested, which is rarely the case. Most rules need not care whether scripting is available or not; they simply look at the resulting DOM, which may or may not have been affected by scripts. For example, one can create an `Audio` instance in JavaScript and have it play back audio to a user without ever touching the DOM; for this, JavaScript as an input aspect _could_ be relevant.

**Comment by WilcoFiers** [comment]
**Proposed response**:

The ACT Task Force is open to adding other input aspects to the note as they get adopted by rule authors. The reason shadow DOM is not included is because it is a feature of the DOM tree. It is not considered its own aspect. As for JavaScript / ECMAScripts, there are currently no rules that use these as input.

**Comment by aglevelaccess** [comment]
Proposed response acceptable.
