### ISSUE TITLE
Level Access Feedback: Unspecified Input Aspects

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#370]
**Suggestion**: Tighten the sentence “For input aspects that are not well defined, an ACT Rule MUST include either a detailed description of the aspect in question, or a reference to a well defined description.”

**Reason**: We’ve noticed that the ACT-R Rules point to testing the Accessibility Tree.  There is no, as far as we understand, formal Accessibility Tree standard.  This means it’s implementation by each different tool developer might be a cause for divergence.  We might consider creating a detailed, shared understanding of some of these terms.

**Comment by WilcoFiers** [comment]
Discussed on the call, proposal to add "accessibility tree" to the input aspects note.

**Comment by maryjom** [comment]
@WilcoFiers We need to assign someone to this.  I'll bring this up as an agenda item. Not to discuss over again...but to get a volunteer.

**Comment by annethyme** [comment]
Currently no rules uses the accessibility tree as en input aspect.
All current definitions that in any way talk about the accessibility tree, talk about DOM and CSS.

**Comment by WilcoFiers** [comment]
**Proposed response**

Whether or not the accessibility tree can be treated as a definition or as an input aspect it a question for rule writers. Because of this, the ACT Task Force believes this feedback has no direct impact on the ACT Rules Format. However, since there is no standard for the accessibility tree, treating it as an input aspect, rather than something that is objectively defined is something that should be considered. If the ACT-R Community Group, or other rule authors decide to add the accessibility tree as a test aspect, the ACT Task Force will add a description of it to the Common Aspects note.

---
@annethyme I think Alistair is correct, that we should treat the accessibility tree as an input aspect. ACT-R rules treat the accessibility tree as a black box. For example, there is no objective / unambiguous description in the accessibility tree definition of whether or not a particular DOM element is included. Depending on how you implement it (and there is no standard for that) you can get different results.

**Comment by aglevelaccess** [comment]
Proposed response acceptable.
