### ISSUE TITLE
Unintended "must" in Introduction

### ISSUE THREAD

**Issue by nitedog** [w3c/wcag-act#372]
Current text:

> An ACT Rule describes what kind of content it applies to and which conditions must be true about the applicable elements for them to meet all expectations of the rule.

Change to:

> An ACT Rule describes what kind of content it applies to and which conditions are true about the applicable elements for them to meet all expectations of the rule.

(remove "must" in the sentence)

**Comment by WilcoFiers** [comment]
@nitedog my understanding is that we can't make changes like that. Am I wrong there?

**Comment by nitedog** [comment]
If this was not intended to be a normative conformance requirement of the specification, then I think we can consider this to be an editorial typo. Same with "should" and "may" addressed in other comments. I will double-check that before our call on Thursday.

**Comment by WilcoFiers** [comment]
Thanks for reporting Shadi. As discussed on the task force call, this issue will be resolved (see #388).
