### ISSUE TITLE
Issue with the "Conformance level" part of Accessibility Requirements Mapping

### ISSUE THREAD

**Issue by annethyme** [w3c/wcag-act#384]
In [4.4 Accessibility Requirements Mapping](https://www.w3.org/TR/act-rules-format/#accessibility-requirements-mapping) we write: 

> Each accessibility requirement in the mapping MUST include the following:
> [...]
> the conformance level associated with the accessibility requirement, if one exists.

... and in the example we write: 

> Success criterion 1.1.1: Non-text content
> - Required for conformance to WCAG 2.0 and WCAG 2.1 level A

However, when looking at the [definition of Conformance Level in WCAG](https://www.w3.org/TR/WCAG21/#cc1), it says: 

> - For Level A conformance (the minimum level of conformance), the Web page satisfies all the Level A Success Criteria, or a conforming alternate version is provided.
> - For Level AA conformance, the Web page satisfies all the Level A and Level AA Success Criteria, or a Level AA conforming alternate version is provided.
> - For Level AAA conformance, the Web page satisfies all the Level A, Level AA and Level AAA Success Criteria, or a Level AAA conforming alternate version is provided.

So it seems that what we are talking about in the Accessibility Requirements Mapping is actually not "conformance level" but just the "level" associated with the success criterion. 
And thus the example should actually be: 

> Success criterion 1.1.1: Non-text content
> - Required for conformance to WCAG 2.0 and WCAG 2.1 level A **_and above_**

... since a Level A success criterion will be required for both Level A/AA/AAA Conformance due to the definition of "conformance level".

**Comment by nitedog** [comment]
@annethyme I think that, since Level AA requires "all the Level A and Level AA Success Criteria", that this addition is not necessary.
