### ISSUE TITLE
Resolve "lang and xml:lang match" feedback

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#417]
Rule: https://act-rules.github.io/rules/5b7ae0

Below is the rest of the feedback, checked off all the things that are resolved. Put a response next to everything that wasn't taken over as suggested.

## RULE REVIEW: HTML LANG AND XML:LANG MATCH

**Anne**: 

- [x] Applicability is using the undefined term "page", which is ambiguous.

- [x] Yes, there are questions about the usage of xml:lang: https://github.com/act-rules/act-rules.github.io/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+5b7ae0+ 
- consider if the xml:lang discussion should be a blocker

**Answer**: Indeed this needs to be resolved. However I do not believe resolving this discussion requires any change to the lang / xml:lang match rule. Other rules are impacted, but this rule can be taken as-is.

- [x] Background links to WCAG 2.0 documents. It should be WCAG 2.1.

- [x] Broken links in Changelog.

**Charu**: 

- [x] The root element of the page, (page is not defined) I would think it should say HTML document

- [x] The current background links for the rule that map to WCAG 2.0 do not mention anything about the failure due to mismatch of the lang and xml:lang, may this could be added as a failure technique.

**Answer**: Makes sense. That's probably one to discuss with AG.

- [x] This rule could use a link to the HTML 5 specification that documents that they should be same if both are applied to the HTML element.
https://www.w3.org/TR/html52/dom.html#the-lang-and-xmllang-attributes

**MJM**: 

- Similar comments to previous rules on the overall template. We need to decide:

  - [x] whether or not to provide a section on implementations within the rule or simply link to an implementations page as part of the reference materials
  - [x] What consists of an implementation? Does it have to correctly identify all pass, fail, and inapplicable results in the test cases, mostly implement, or simply attempt to implement the rule? 
  - [x] How many implementations are needed to publish the rule? 1, 2, 3?

- [x] I agree with Kathy that the note in the accessibility support is more appropriate to be under the assumptions. You're assuming that there are no accessibility support issues if xml:lang is also used and that assistive technologies use lang over xml:lang when both are present, correct?

- [x] As related to the test cases, the rule says you need to test for a valid lang tag, which is defined with a link to the definition of valid tags. I don't see test cases that check all of the potential correct tags are listed here: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry. If this rule doesn't intend to check that the lang tag is actually valid, then there needs to be an assumption that the lang in the lang tag, if it exists, is a valid one from that list.

**Answer**: The ACT Rules Format does not require test cases to be exhaustive. Often that's not possible, but even when it is, the intent of test cases isn't to ensure every implementation is 100% consistent. 

- [x] For SiteImprove & Axe-core implementation, what does "untested" mean? Is there a new test case that hasn't been checked yet? Should that be tested and results documented before publishing the rule? Should that be tested before listing them as an implementation?

**Answer**: See previous discussions on "untested". Summary, we'll change it, but don't think it impacts whether or not the rule can be published.

- [x] Issue #659 is still open and seems to be an issue to need fixing before publication.

**Kathy**: 

- [x] Note under Exception can go under Assumption: 
  > Note: HTML 5 specification requires the lang and xml:lang attributes to match exactly. This is not known to impact accessibility, which is why it is permitted in this rule.

**Answer**: This is inconsistent with other rules where we've used notes. I think including a note on the difference between accessible HTML and valid HTML belongs in the expectation. We are not assuming that invalid HTML can still be accessible. This is a fact, as bas I know, which is why valid HTML isn't required for accessibility.

- [x] SVG test case expected inapplicable, Some implementations were untested, which is acceptable to me.

**Answer**: See previous discussions on "untested". Summary, we'll change it, but don't think it impacts whether or not the rule can be published.

**Romain**: 

- [x] See issue https://github.com/act-rules/act-rules.github.io/issues/659

- [x] I'm not sure why the empty values are not covered by this rule. This wouldn't require too big a change, and would generally augment its applicability and usefulness, no?

**Answer**: This is addressed by the "HTML has lang attribute" rule. The ACT-R community group has tried to minimise overlap between rules wherever reasonable. 

- [x] The applicability says "the root element of the page". Shouldn't it say: "Any root element of a page" or "the root element of any page" so that the rule can be applied to a collection of pages?

**Comment by tbostic32** [comment]
From follow on survey, the issues that don't seem to have been addressed yet.
Kathy:
- [ ] Under Assumptions it says:
    > "This rule doesn't test if the attribute is needed to comply to WCAG."

It's not clear to me what this is saying since the lang attribute is needed to comply with WCAG. Is it saying that the xml lang isn't needed? 

Mary Jom:
- [ ] I think that the link to the HTML spec that says that the two lang tags should match should be added to the background section. Link: https://www.w3.org/TR/html52/dom.html#the-lang-and-xmllang-attributes

**Comment by jkodu** [comment]
Notes on [comment](https://github.com/w3c/wcag-act/issues/417#issuecomment-578440138) above:

@Kathy, we use the same assumption in a variety of `lang` rules. Given the precursor statement, I believe this statement is concise.

> This rule assumes that the presence of a `lang` attribute is being used to comply to WCAG. This rule doesn't test if the attribute is needed to comply to WCAG.

@maryjom - link has been updated (PR - https://github.com/act-rules/act-rules.github.io/pull/1155)

**Comment by kasperisager** [comment]
@maryjom @jkodu 

Per the MoU between the W3C and the WHATWG:

> Normative references from W3C specifications to material that is in the HTML and DOM specifications shall reference the whatwg.org Living Standard both in-line and in the Normative References section. W3C advises that W3C specifications also reference the W3C Recommendation in the References section.

https://www.w3.org/2019/04/WHATWG-W3C-MOU.html#referencing

Even though the link in question isn't a normative reference, I still think it would be weird having informative references to the W3C version of the HTML spec when all normative references are required to reference the WHATWG version.

**Comment by Jym77** [comment]
> @Kathy, we use the same assumption in a variety of `lang` rules. Given the precursor statement, I believe this statement is concise.
> 
> > This rule assumes that the presence of a `lang` attribute is being used to comply to WCAG. This rule doesn't test if the attribute is needed to comply to WCAG.

@jkodu After a good discussion with other members of the ACT rules CG, https://github.com/act-rules/act-rules.github.io/pull/1153, we should probably update the assumption in the same way for all `lang` rules.

**Comment by jkodu** [comment]
@WilcoFiers 

I went through all of the above requested changes. They have all been catered to, please feel free to promote this further.

**Comment by WilcoFiers** [comment]
Actually this one seems done. Closing the issue.
