### ISSUE TITLE
New rule: id attribute value is unique

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#426]
[Link to the rule](https://act-rules.github.io/rules/3ea0c8)
[link to the survey results](https://www.w3.org/2002/09/wbs/93339/IDisUnique/results)
[link to the minutes from TF]()

## Moe

- [ ] In outcome mappings, it states that passed outcomes require further testing. I don't see why. Please add an explicit statement as to why this is necessary.

- [ ] In outcome mappings, it states that passed outcomes require further testing. I don't see why. Please add an explicit statement as to why this is necessary. https://github.com/act-rules/act-rules.github.io/issues/1079

## Romain

- [ ] The rule lists technique H94 (no duplicate attributes) as a background reference, but I don’t think it’s relevant for this rule.

- [ ] Is it planned to use another rule to test that the ID attribute is non-empty? Or should it be included in this rule?

## Jon

- [ ] The only comment I have is that the pass #4 is an iFrame without an accessible name. Passes should not fail other rules and should be good examples of coding.

**Comment by WilcoFiers** [comment]
Assigned to @Jym77

**Comment by Jym77** [comment]
> [Link to the rule](https://act-rules.github.io/rules/3ea0c8)
> [link to the survey results](https://www.w3.org/2002/09/wbs/93339/IDisUnique/results)
> link to the minutes from TF

The link to survey is protected and I cannot see it with my W3C credentials. The link to the minutes is simply missing.

> ## Moe
> * [ ]  In outcome mappings, it states that passed outcomes require further testing. I don't see why. Please add an explicit statement as to why this is necessary.
> * [ ]  In outcome mappings, it states that passed outcomes require further testing. I don't see why. Please add an explicit statement as to why this is necessary. [act-rules/act-rules.github.io#1079](https://github.com/act-rules/act-rules.github.io/issues/1079)

Added in note in https://github.com/act-rules/act-rules.github.io/pull/1147

> ## Romain
> * [ ]  The rule lists technique H94 (no duplicate attributes) as a background reference, but I don’t think it’s relevant for this rule.

Removed in https://github.com/act-rules/act-rules.github.io/pull/1145

> * [ ]  Is it planned to use another rule to test that the ID attribute is non-empty? Or should it be included in this rule?

I do not think this should be part of the same rule (in order to keep rules simples). No rule to check that `id` are not empty is currently planned, but it could be a nice addition to our set of rules.

> ## Jon
> * [ ]  The only comment I have is that the pass #4 is an iFrame without an accessible name. Passes should not fail other rules and should be good examples of coding.

Title added in https://github.com/act-rules/act-rules.github.io/pull/1146

**Comment by WilcoFiers** [comment]
Because AG isn't considering this rule for publication, we're closing this thread.
