### ISSUE TITLE
Resolve "iFrame Element has Accessible Name" feedback

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag-act#428]
### Romain Deltour
[ ] I'm not sure I understand this assumption: what would be an iframe that is *not* used as a UI component? Maybe an example would help disambiguate that?
[ ] The accessibility support section says there are no major issues known; however, the glossary entry for "accessible name" describes some interoperability issues with the name and description computation. Shouldn't these issues be mentioned in the rule’s accessibility support?

### Charu Pandhi
[ ] It is not clear what exactly is conveyed by the assumption statement "The rule assumes that the target iframe is used as a user interface component." what other ways can an iframe be used? What about iframe with role of presentation?
[ ] Example 3 and example 7 are kinda duplicates. Should we add an example when iframe is used for presentation? or with role=presentation.

### Wilco Fiers
[ ] I think the assumption can be made a little clearer though. Not a blocker. There's an issue open on the ACT-R repo to clarify the assumptions.
[ ] Although more implementors would be preferable. I'm reaching out to the implementors to update. Used to have more of them.

### Kathy Eng
[ ] [Pull request 6](https://github.com/act-rules/act-rules-implementation-trusted-tester/pull/6) is Trusted Tester implementation.

### Moe Kraft
[ ] Use proper case in Applicability section.

Applicability

The rule applies to iframe elements that are included in the accessibility tree.

Note: The frame element is deprecated. This rule does not consider frame or frameset elements. <==Added the before frame element and separated into two sentences both starting with uppercase.
[ ] I think you should expand upon or explain why "All passed outcomes: further testing needed." It makes sense when you see passed example 4, <iframe title=":-)" src="/test-assets/SC4-1-2-frame-doc.html"> </iframe>. You need to validate that the accessible name is meaningful and describes the element. But would be good to state this explicitly maybe in the passed examples. See [github issue #1078](Github issue: https://github.com/act-rules/act-rules.github.io/issues/1078)

### Trevor Bostic
[ ] From the background section, how is this rule relevant to section 2.4.1? I don't use iframes much, but I am just not sure what the design pattern is that links them to bypass blocks is. -- After a bit of digging I found this: https://www.w3.org/WAI/WCAG21/Techniques/html/H70 which answers my question.

**Comment by jkodu** [comment]
> Rule: https://act-rules.github.io/rules/cae760

**Comment by jkodu** [comment]
It seems like all the above points were addressed.

Linking to another issue for this rule - https://github.com/w3c/wcag-act/issues/435
