### ISSUE TITLE
Resolve "HTML page language is valid" feedback

### ISSUE THREAD

**Issue by kengdoj** [w3c/wcag-act#429]
Rule: [https://act-rules.github.io/rules/bf051a](https://act-rules.github.io/rules/bf051a)
[Survey Results](https://www.w3.org/2002/09/wbs/93339/ValidPageLang2/results) 

# RULE REVIEW: HTML PAGE LANGUAGE IS VALID #

- [ ] [Make lang matching less strict (bf051a, de46e4)](https://github.com/act-rules/act-rules.github.io/issues/1105)

- [ ] [Lang verification (bf051a and de46e4) extends beyond requirements](https://github.com/act-rules/act-rules.github.io/issues/1087)

## Detlev Fischer ##

- [ ] The applicability section says that "iframe and object elements are not applicable "to then say that a wrong lang attribute may still create problems. This may be slightly confusing. If it can cause problems, why is it not applicable? Because it RARELY causes problems? Because it is difficult to set the correct language on embedded content?

- [ ] Possibly clarify the note to make it explicit that iframe / object lang attr are excluded, and why.

## Charu Pandhi ##

- [ ] Understand iframe or embedded objects are inapplicable for this rule. The note says an incorrect lang attribute on them could still cause a problem, if so can we clarify why? Will there be another rule to test that? and also maybe add a test case to that extent may help.

## Romain Deltour ##

- [ ] I don't understand what is meant by: "This rule doesn't test if the attribute is needed to comply to WCAG."

This rule essentially checks that:

- the lang attribute is syntactically correct
- the primary language subtag is well-known

- [ ] Question 1: Is it assumed or well known that invalid sub tags *after the primary language subtag* are causing accessibility issues ? (e.g. is "en-US-GB" really going to cause accessibility issues?)

- [ ] Question 2: What about grandfathered tags (e.g. `i-lux`, `i-navajo`)? My understanding is that they're allowed, but maybe this should be made explicit in the "valid language subtag" definition.

## Kathy Eng ##

- [ ] [Failed example 2](https://act-rules.github.io/rules/bf051a#failed-example-2) 

> The lang attribute value has a valid primary language subtag, but a syntactically invalid region subtag. `<html` lang="en-US-GB"></html>

should not fail since "This rule checks that the lang attribute of the root element of an HTML page has a valid primary language subtag."

## Mary Jo Mueller ##

- [ ] Looks like Trusted Tester has implementation data for this rule submitted in issue 1045.

- [ ] Agree with others' concerns about the sub-language. Since this rule is to check the validity/existence of a primary language tag it shouldn't check for sub-language.

## Jonathan Avila ##

- [ ] Not holding up this rule -- but I did log a comment indicating that this rule is very heavy. This test along requires 9k of file size just to test the 9k sub language codes. While this isn't an issue for many checker -- for checkers that are dynamic and run live this can be very heavy.

## Wilco Fiers ##

- [ ] I created a PR for this, minor changes, but I think they should happen:
[https://github.com/act-rules/act-rules.github.io/pull/1036](https://github.com/act-rules/act-rules.github.io/pull/1036)

**Comment by WilcoFiers** [comment]
Assigned to @Jym77

**Comment by Jym77** [comment]
> Rule: https://act-rules.github.io/rules/bf051a
> [Survey Results](https://www.w3.org/2002/09/wbs/93339/ValidPageLang2/results)
> 
> # RULE REVIEW: HTML PAGE LANGUAGE IS VALID
> * [ ]  [Make lang matching less strict (bf051a, de46e4)](https://github.com/act-rules/act-rules.github.io/issues/1105)

Should be fixed in https://github.com/act-rules/act-rules.github.io/pull/1106

> * [ ]  [Lang verification (bf051a and de46e4) extends beyond requirements](https://github.com/act-rules/act-rules.github.io/issues/1087)

Seems to have been escalated to https://github.com/w3c/wcag/issues/1028

> ## Detlev Fischer
> * [ ]  The applicability section says that "iframe and object elements are not applicable "to then say that a wrong lang attribute may still create problems. This may be slightly confusing. If it can cause problems, why is it not applicable? Because it RARELY causes problems? Because it is difficult to set the correct language on embedded content?
> * [ ]  Possibly clarify the note to make it explicit that iframe / object lang attr are excluded, and why.

Done in https://github.com/act-rules/act-rules.github.io/pull/1152

> ## Charu Pandhi
> * [ ]  Understand iframe or embedded objects are inapplicable for this rule. The note says an incorrect lang attribute on them could still cause a problem, if so can we clarify why? Will there be another rule to test that? and also maybe add a test case to that extent may help.

Done in https://github.com/act-rules/act-rules.github.io/pull/1152

> ## Romain Deltour
> * [ ]  I don't understand what is meant by: "This rule doesn't test if the attribute is needed to comply to WCAG."

Explained in https://github.com/act-rules/act-rules.github.io/pull/1153

> This rule essentially checks that:
> 
> * the lang attribute is syntactically correct
> * the primary language subtag is well-known
> * [ ]  Question 1: Is it assumed or well known that invalid sub tags _after the primary language subtag_ are causing accessibility issues ? (e.g. is "en-US-GB" really going to cause accessibility issues?)

It can cause accessibility issues in some case. A notorious example is `zh-yue` (Cantonese) and `zh-cmn` (Mandarin) which are written similarly but pronounced very differently (to the point of not being mutually understandable). Thus, an incorrect secondary tag may cause screen readers to use wrong pronunciation and cause an accessibility issue. This is, however, rather an exception than a rule (as far a secondary tags are concerned).

Moreover, the matching of tags has been greatly simplified in https://github.com/act-rules/act-rules.github.io/pull/1106 and that should answer this concern.

> * [ ]  Question 2: What about grandfathered tags (e.g. `i-lux`, `i-navajo`)? My understanding is that they're allowed, but maybe this should be made explicit in the "valid language subtag" definition.

They have been explicitly skipped in https://github.com/act-rules/act-rules.github.io/pull/1106

> ## Kathy Eng
> * [ ]  [Failed example 2](https://act-rules.github.io/rules/bf051a#failed-example-2)
> 
> > The lang attribute value has a valid primary language subtag, but a syntactically invalid region subtag. `<html` lang="en-US-GB">
> 
> should not fail since "This rule checks that the lang attribute of the root element of an HTML page has a valid primary language subtag."

This should be fixed as part of https://github.com/act-rules/act-rules.github.io/pull/1106

> ## Mary Jo Mueller
> * [ ]  Looks like Trusted Tester has implementation data for this rule submitted in issue 1045.

@jkodu do you know the status of this implementation data?

> * [ ]  Agree with others' concerns about the sub-language. Since this rule is to check the validity/existence of a primary language tag it shouldn't check for sub-language.

This should be fixed as part of https://github.com/act-rules/act-rules.github.io/pull/1106

**Comment by WilcoFiers** [comment]
Assigned to Jean-Yves

**Comment by Jym77** [comment]
Every thing should be be done now and rule is ready for another round…

**Comment by kengdoj** [comment]
For [Issue #449: Consistency with notes for out of scope content](https://github.com/w3c/wcag-act/issues/449):

Current note under Applicability:
> Note: html elements within iframe and object elements are not applicable as iframe and object elements create nested browsing contexts. These elements can embed any third party content, making testing difficult. As these elements are meant to provide a layer of isolation, the language of the parent browsing context may not be inherited. Thus, embedded documents with an invalid lang attribute can cause accessibility issues. This should be tested separately.

**Option 1: Remove note and modify second bullet under Applicability**
> This rule applies to any document element if it is an html element that:
> - has a lang attribute that is neither empty (“”) nor only ASCII whitespace; and
> - is in a top-level browsing context; and
> - has a node document with a content type of text/html.

Add ( ): - is in a top-level browsing context (not an embedded resource within a frame or object element)

**Option 2: Remove note and provide a definition of "HTML page".**
Modify [definition of web page from Understanding 2.4.2 Page Titled](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html#dfn-web-page):

> HTML page
> a non-embedded resource obtained from a single URI using HTTP plus any other resources that are used in the rendering or intended to be rendered together with it by a user agent

**Comment by WilcoFiers** [comment]
Accepted pending an update to the title.

**Comment by WilcoFiers** [comment]
Title has been updated, rule is accepted and ready for publication. Needs a PR into w3c/wcag-act-rules

**Comment by WilcoFiers** [comment]
PR got merged, issue is closed.
