### ISSUE TITLE
Resolve "Image has accessible name" feedback

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#430]
## Kathy

- [x] With Rule Description: This rule checks that each image *that is not marked as decorative*, has an accessible name, and Expectation: Each target element has an accessible name that is not empty (""), or is marked as decorative, the following "Pass" test cases (5, 6, 7) should be Inapplicable because they are marked as decorative:

**Answer**: Resolved in https://github.com/act-rules/act-rules.github.io/pull/1218

- [ ] Failed Example 4 - The HTML img element has an empty accessible name. Trusted Tester would consider this a decorative img and would mark this one Inapplicable. 

**Answer**: Testing need to confirm. VO in Safari seems to ignore, but VO in Chrome does not. Need to know about other AT too. Data coming shortly.

## Trevor

- [x] We should remove passed example 8 for reasons discussed previously.

- [x] For parity, I think we should add a passed example of div positioned off screen that does have an accessible name or is marked as decorative. I think this helps with clarity on the positioning not being the failing factor.

- [x] We use "empty accessible name" inconsistently. Failed example 4 has whitespace in the alt text (i.e., atl=" ") vs the alt text being null (i.e., alt="")

## Kasper

- [x] https://github.com/act-rules/act-rules.github.io/issues/446

## Wilco

- [x] https://github.com/act-rules/act-rules.github.io/issues/1124

- [x] The first note in the expectation should make clear that alt="" only works for img elements.

- [x] Missing link to understanding doc in background section

- [x] Inapplicable 1 should have an accessible name.

**Comment by WilcoFiers** [comment]
There are three PRs open, once these are merged this can go back into survey:
- https://github.com/act-rules/act-rules.github.io/pull/1300
- https://github.com/act-rules/act-rules.github.io/pull/1301
- https://github.com/act-rules/act-rules.github.io/pull/1302

There is also PR https://github.com/act-rules/act-rules.github.io/pull/1208, but I don't believe this needs to be resolved before we publish this rule.

**Comment by maryjom** [comment]
@WilcoFiers @daniel-montalvo I think there was also some test data we were waiting on for this. My recollection was that Daniel volunteered to check what happened in various screen readers.

Failed Example 4 - The HTML img element has an empty accessible name. Trusted Tester would consider this a decorative img and would mark this one Inapplicable.
Answer: Testing needed to confirm. VO in Safari seems to ignore, but VO in Chrome does not. Need to know about other AT too. Data coming shortly.

**Comment by maryjom** [comment]
[Survey results](https://www.w3.org/2002/09/wbs/93339/ACTImageAccName2/results)
