### ISSUE TITLE
Resolve "HTML has lang attribute" feedback

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag-act#436]
[HTML has lang attribute](https://act-rules.github.io/rules/b5c3f8)
[Survey results](https://www.w3.org/2002/09/wbs/93339/HTMLLang2/results) concluded 14 Feb.

## Wilco Fiers
- [x] I think the assumption should be clarified.
- [x] The axe-core result is partially consistent. Would like to know the opinion of the group on this. I don't think that should block this rule though.
**Mary Jo Mueller commented** _As long as there is one implementation with results that are the expected results it is fine._
**Kathy Eng commented** _I also wouldn't hold up a rule if an implementation is partially consistent. However, if 3 is the required number of implementations, this one does not have enough yet._

## Kathy Eng
- [x] Suggest adding <html lang="123"></html> as a pass example since this rule checks only that lang attribute is non-empty and not whitespace.
**Mary Jo Mueller commented** _I don't think it's necessary to have a second test case with an invalid, but not empty lang value - Pass Example 1 with lang='en' is sufficient, as it is a non-empty value._
- [x] more implementations if minimum is not met

**Comment by WilcoFiers** [comment]
All these comments were resolved a while ago. I think this rule can be updated.

**Comment by WilcoFiers** [comment]
Correction, all open feedback was resolved before this rule was published. No further action needed.
