### ISSUE TITLE
New rule: Orientation of the page is not restricted using CSS transform property

### ISSUE THREAD

**Issue by kasperisager** [w3c/wcag-act#438]
The ACT-Rules community group has completed work on Orientation of the page is not restricted using CSS transform property. We would like to see this rule be added to the WCAG ruleset. You can find the rule here:

**Rule title**: Orientation of the page is not restricted using CSS transform property
**Rule id**: b33eff
**Link to the rule**: https://act-rules.github.io/rules/b33eff
**License**: W3C Software And Document Notice And License
**Implementors**:
- Axe Core by Deque Systems
- QualWeb by Faculdade de Ciências da Universidade de Lisboa
- SortSite by PowerMapper

**Comment by WilcoFiers** [comment]
Related to #445
