### ISSUE TITLE
Resolve "Link has non-empty accessible name" feedback

### ISSUE THREAD

**Issue by kasperisager** [w3c/wcag-act#439]
Rule: https://act-rules.github.io/rules/c487ae
Survey results: https://www.w3.org/2002/09/wbs/93339/ACTLinkHasName/results

## Charu Pandhi

- [x] Should the rule make it clear that `<a>` without an `href` does not have the semantic role of link and also maybe have an example?

- [ ] Should the rule allow the `title` attribute to provide accessible name? H33 says `title` should be used to supplement the link text (https://www.w3.org/WAI/WCAG21/Techniques/html/H33.html).

## Kathy Eng

- [x] https://github.com/act-rules/act-rules.github.io/issues/1185

- [x] This rule is checking that a link has accname and not describing the link's purpose. Not a blocker, but I don't think the accessibility requirements mapping section should include these:

    - 2.4.4 Link Purpose (In Context) (Level: A) - The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general.

    - 2.4.9 Link Purpose (Link Only) (Level: AAA) - A mechanism is available to allow the purpose of each link to be identified from link text alone, except where the purpose of the link would be ambiguous to users in general.

    - G91: Providing link text that describes the purpose of a link - The objective of this technique is to describe the purpose of a link in the text of the link.

## Kasper Isager

- [x] The rule is affected by this open issue: https://github.com/act-rules/act-rules.github.io/issues/1177. Consider a case such as this:

    ```html
    <a role="none" href="#"></a>
    ```

    The rule considers this element to have a role of "none", not "link", and will therefore not apply to it. However, the element will actually be exposed with a role of "link" and no accessible name due to presentational roles conflict resolution: https://www.w3.org/TR/wai-aria/#conflict_resolution_presentation_none. It should therefore fail the rule.

## Wilco Fiers

- [ ] I think the examples could be improved. The images do not have a valid `src`, which makes some of these a little questionable. Additionally I think rules where no native link is used, it would be better to ensure those element still behave as though they were links, otherwise it's somewhat questionable if 2.4.4 / 2.4.9 applies. For example, clicking them changes the page URL.

## Mary Jo Mueller

- [x] Agree with Charu. `<a>` without an `href` isn't semantically a link and doesn't require an accessible name, as it won't be presented to AT as a link. This should be included as an "inapplicable" test case.

- [x] Agree with Kasper. Issue 1177 needs resolving here, as we don't want to pass elements that could potentially cause accessibility errors. Agree with Kathy that issue 1185 is not a blocker to publication, but if this rule is going back for changes, might as well fix this too.

**Comment by WilcoFiers** [comment]
Awaiting https://github.com/act-rules/act-rules.github.io/pull/1255

**Comment by carlosapaduarte** [comment]
> ## Charu Pandhi
> 
>     * [x]  Should the rule make it clear that `<a>` without an `href` does not have the semantic role of link and also maybe have an example?

Included an example (Inapplicable example 6)
 
>     * [ ]  Should the rule allow the `title` attribute to provide accessible name? H33 says `title` should be used to supplement the link text (https://www.w3.org/WAI/WCAG21/Techniques/html/H33.html).

Passed examples 5 and 6 illustrate the use of `title` in the accessible name computation 

> ## Kathy Eng
> 
>     * [x]  [act-rules/act-rules.github.io#1185](https://github.com/act-rules/act-rules.github.io/issues/1185)

Fixed as part of [act-rules/act-rules.github.io/pull/1216](https://github.com/act-rules/act-rules.github.io/pull/1216)

>     * [x]  This rule is checking that a link has accname and not describing the link's purpose. Not a blocker, but I don't think the accessibility requirements mapping section should include these:
>       
>       * 2.4.4 Link Purpose (In Context) (Level: A) - The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general.
>       * 2.4.9 Link Purpose (Link Only) (Level: AAA) - A mechanism is available to allow the purpose of each link to be identified from link text alone, except where the purpose of the link would be ambiguous to users in general.
>       * G91: Providing link text that describes the purpose of a link - The objective of this technique is to describe the purpose of a link in the text of the link.

According to Wilco's [comment](https://github.com/act-rules/act-rules.github.io/pull/1256#pullrequestreview-385407585) the TF agreed to leave this as is.

> ## Kasper Isager
> 
>     * [x]  The rule is affected by this open issue: [act-rules/act-rules.github.io#1177](https://github.com/act-rules/act-rules.github.io/issues/1177). Consider a case such as this:
>       ```
>       <a role="none" href="#"></a>
>       ```
>       
>       
>       The rule considers this element to have a role of "none", not "link", and will therefore not apply to it. However, the element will actually be exposed with a role of "link" and no accessible name due to presentational roles conflict resolution: https://www.w3.org/TR/wai-aria/#conflict_resolution_presentation_none. It should therefore fail the rule.

Fixed as part of [https://github.com/act-rules/act-rules.github.io/pull/1189](https://github.com/act-rules/act-rules.github.io/pull/1189)

> ## Wilco Fiers
> 
>     * [ ]  I think the examples could be improved. The images do not have a valid `src`, which makes some of these a little questionable. Additionally I think rules where no native link is used, it would be better to ensure those element still behave as though they were links, otherwise it's somewhat questionable if 2.4.4 / 2.4.9 applies. For example, clicking them changes the page URL.

All examples improved.

> ## Mary Jo Mueller
> 
>     * [x]  Agree with Charu. `<a>` without an `href` isn't semantically a link and doesn't require an accessible name, as it won't be presented to AT as a link. This should be included as an "inapplicable" test case.
> 
>     * [x]  Agree with Kasper. Issue 1177 needs resolving here, as we don't want to pass elements that could potentially cause accessibility errors. Agree with Kathy that issue 1185 is not a blocker to publication, but if this rule is going back for changes, might as well fix this too.

**Comment by carlosapaduarte** [comment]
@WilcoFiers the rule is ready for another round of reviews

**Comment by WilcoFiers** [comment]
Rule has been accepted on the TF call. As soon as https://github.com/act-rules/act-rules.github.io/pull/1360 is merged, this will go into CFC.

**Comment by carlosapaduarte** [comment]
> Rule has been accepted on the TF call. As soon as [act-rules/act-rules.github.io#1360](https://github.com/act-rules/act-rules.github.io/pull/1360) is merged, this will go into CFC.

@wilco, PR#1360 has been merged

**Comment by maryjom** [comment]
The CFC has passed as of 16 July. Can this issue be closed or do we keep it open until the pull request is ready?

**Comment by WilcoFiers** [comment]
Rule has been approved. The pull request for it is here: https://github.com/w3c/wcag-act-rules/pull/32
