### ISSUE TITLE
New rule: svg element with explicit role has accessible name

### ISSUE THREAD

**Issue by Jym77** [w3c/wcag-act#440]
The ACT-Rules community group has completed work on rule "svg element with explicit role has accessible name". We would like to see this rule be added to the WCAG ruleset. You can find the rule here:

**Rule title**: svg element with explicit role has accessible name
**Rule id**: 7d6734
**Link to the rule**: https://act-rules.github.io/rules/7d6734
**License**: W3C Software And Document Notice And License
**Implementors**:
- Axe Core (Deque System)
- Qualweb (University of Lisbon)
- SortSite (PowerMapper)

**Comment by WilcoFiers** [comment]
Rule has been approved, PR needed.
