### ISSUE TITLE
New rule: Image filename is accessible name for image

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#441]
The ACT-Rules community group has completed work on rule "Image filename is accessible name for image". We would like to see this rule be added to the WCAG ruleset. You can find the rule here:

**Rule title**: Image filename is accessible name for image
**Rule id**: 9eb3f6
**Link to the rule**: https://act-rules.github.io/rules/9eb3f6
**License**: W3C Software And Document Notice And License
**Implementors**:
- Axe Core (Deque System)
- SortSite (PowerMapper)

**Comment by WilcoFiers** [comment]
Feedback is in #447
