### ISSUE TITLE
New rule: aria-* attribute is defined in WAI-ARIA

### ISSUE THREAD

**Issue by jkodu** [w3c/wcag-act#442]
The ACT-Rules community group has completed work on the rule: "aria-* attribute is defined in WAI-ARIA".

We would like to see this rule be added to the WCAG ruleset. You can find the rule here:

**Rule title:** aria-* attribute is defined in WAI-ARIA
**Rule id:** 5f99a7
**Link to the rule:** https://act-rules.github.io/rules/5f99a7
**License:** W3C Software And Document Notice And License
**Implementors:**
- Alfa (Siteimprove)
- Qualweb (University of Lisbon)

**Comment by WilcoFiers** [comment]
Survey was done, feedback in #452
