### ISSUE TITLE
Resolve "Orientation of the page is not restricted using CSS transform property" feedback

### ISSUE THREAD

**Issue by cpandhi** [w3c/wcag-act#445]
[Orientation of the page is not restricted using CSS transform property](https://act-rules.github.io/rules/b33eff)
[Survey results](https://www.w3.org/2002/09/wbs/93339/ACTORIENTATION/results)

## Trevor Bostic

- [ ] I am having a hard time understanding the expectation. I am wondering if more clarification can be given. Would it break spec to include an image or images that show what exactly is being tested? The rule name is about orientation of the page not being restricted, but the applicability and expectation are given for specific elements.
 _**Mary Jo commented:**_ To Trevor's comment - I think the expectation is written as a long, complex sentence. Can it be simplified? I agree that adding an image showing what it means would help.
- [ ] Is there a reason to link to the stylesheet in failed example 1? We typically include all of the code in the example and its only 3 or 4 lines.
- [ ] Is there a reason to link to the stylesheet in failed example 1? We typically include all of the code in the example and its only 3 or 4 lines.

## Patrick Lauke

- [ ] Wondering if the precise "90 degrees" may not offer an escape hatch here that is not necessarily present in the wording of WCAG itself. while admittedly this will be the most common case, what if the rotation is "85 degrees" for whatever reason (maybe to better fit into the different orentation's layout ... it might start off at a very subtle 5 degree angle in landscape, but in portrait may align to a perpendicular layout grid, so only rotated by that amount instead.

- [ ] I would add a failure example where a rotation is already applied to start with in one orientation (e.g. a <div> at a "jaunty angle" of a few degrees) and then rotated further (by equivalent of 90 degrees) in the other orientation.

## Mary Jo

- [ ] It would be great to have an illustration for the expectations.

**Comment by kasperisager** [comment]
The pull request addressing the outstanding feedback is currently in final call until June 16.

**Comment by maryjom** [comment]
Here is a link to the [Survey results](https://www.w3.org/2002/09/wbs/93339/ACTPageOrientation/results). However, the survey due date had to be extended to 30 July due to a lack of enough responses.

**Comment by maryjom** [comment]
@cpandhi Please open an issue for the comments reported in the survey results and include pointers to the meeting minutes where this issue was discussed. This survey was discussed in the following meetings:
- [July 23 meeting](https://www.w3.org/2020/07/23-wcag-act-minutes.html#item04)
- [July 30 meeting](https://www.w3.org/2020/07/30-wcag-act-minutes.html#item03)

**Comment by WilcoFiers** [comment]
Closed by #481
