### ISSUE TITLE
Resolve "Button has an accessible name" feedback

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag-act#451]
[Button has an accessible name](https://act-rules.github.io/rules/97a4e1)
[Survey results](https://www.w3.org/2002/09/wbs/93339/ButtonName2/results)

## Trevor Bostic
- [x] It may be worth linking to: https://www.w3.org/TR/html-aria/#docconformance in the background as a guide for implicit roles. At least for me, I didn't realize that a summary elements implicit role was button.

> **Answer:** Summary isn't a button, this was a mistake which has been fixed.

## Kathy Eng
- [x] Failed example 2: This button element has no accessible name. The value attribute does not provide an accessible name for button elements, only for input elements.
`<button type="button" value="read more"></button>` Please clarify: Value is part of accessible name comp for input type = button|submit|reset, not all input types. (https://w3c.github.io/html-aam/#input-type-button-input-type-submit-and-input-type-reset)

- [x] Open issue - [https://github.com/act-rules/act-rules.github.io/issues/1149](Issue 1149)

## Kasper Isager
- [x] Open issue - [https://github.com/act-rules/act-rules.github.io/issues/1169](Issue 1169)

## Mary Jo Mueller
- [x] Agree with Kasper's comment. Trevor's comment on #4 is related, as that document isn't super clear about the implicit role. The link Kasper provided in issue 1169 seems clearer to me. Although I'm not sure the rule can point to an editor's draft.
- [x] While you're making changes, consider adding the link to the mappings to show the reasoning behind making that test case inapplicable.

> **Answer**: As above

**Comment by WilcoFiers** [comment]
All feedback has been addressed. Lets put this one back into survey so we can get this to the latest version.

**Comment by WilcoFiers** [comment]
Approved for publication, pending at least 1 complete implementation.

**Comment by WilcoFiers** [comment]
We have new implementations. This rule can go to CFC.

**Comment by maryjom** [comment]
This rule has passed CFC as of 23 July. @WilcoFiers Do we close this issue or leave it open until the PR is ready?

**Comment by WilcoFiers** [comment]
Rule has been approved, pull request for it is here: https://github.com/w3c/wcag-act-rules/pull/34
