### ISSUE TITLE
New rule: ARIA state or property is permitted

### ISSUE THREAD

**Issue by Jym77** [w3c/wcag-act#453]
The ACT-Rules community group has completed work on "ARIA state or property is permitted". We would like to see this rule be added to the WCAG ruleset. You can find the rule here:

**Rule title**: ARIA state or property is permitted
**Rule id**: 5c01ea
**Link to the rule**: https://act-rules.github.io/rules/5c01ea
**License**: W3C Software And Document Notice And License
**Implementors**:
- Alfa (Siteimprove)
- axe-core (Deque Systems)
- Qualweb (University of Lisbon)

**Comment by WilcoFiers** [comment]
Survey completed, had some editorial comments that need to be addressed. Aside from that this rule is going on hold. The TF wants to prioritise WCAG rules.
