### ISSUE TITLE
New Rule: `audio` or `video` avoids automatically playing audio

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag-act#454]
The ACT-Rules community group has completed work on the following rule:
* Audio or Video Avoids Automatically Playing Audio (composite rule)
  * Audio Or Video That Plays Automatically Has A Control Mechanism (atomic rule)
  * Audio Or Video That Plays Automatically Does Not Exceed 3 Seconds (atomic rule)

We would like to see this set of rules be added to the WCAG rule set. You can find the rule here:
https://act-rules.github.io/rules/80f0bf

**Rule title**: `audio` or `video` avoids automatically playing audio
**Rule id**: 80f0bf
**Link to the rule**: https://act-rules.github.io/rules/80f0bf
**License**: W3C Software And Document Notice And License
**Implementors**:
- Axe Core by Deque Systems
- QualWeb by Faculdade de Ciências da Universidade de Lisboa
- SortSite by PowerMapper

**Comment by maryjom** [comment]
[Survey results](https://www.w3.org/2002/09/wbs/93339/ACTAutoPlay/results) from review completed on 28 May. Issues found and [Issue 456](https://github.com/w3c/wcag-act/issues/456) was opened.

I think this one can be closed because a new issue was opened.

**Comment by WilcoFiers** [comment]
Closing, because we have an issue with the feedback in it.
