### ISSUE TITLE
Resolve "HTML page has title" feedback 

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#463]
Rule: https://act-rules.github.io/rules/2779a5
Survey results: https://www.w3.org/2002/09/wbs/93339/ACTPAGETITLE2/results

### Wilco

- [ ] https://github.com/act-rules/act-rules.github.io/issues/1091 I think this needs to be clarified in the understanding docs of 4.1.1, not in this rule.

### Detlev

- [ ] I think it would be useful for readers of this rule to be aware that 2.4.2 will need an additional check for the value of title ("...that describe topic or purpose") to avoid the impression that this rule alone can be sufficient to PASS 2.4.2. We know that, but do others? I think it increases the value if a rule conveys such dependencies to less informed readers. Possibly the place for that may be section "Assumptions".

**Suggestion (Wilco)**: Change the rule to include "non-empty" in the title

### Kathy

- [x] Passed Example 2: This page has a title element that is for the entire page, including content in the iframe without its own title.
  - This test does not check for a title that describes content purpose, so including "content in the iframe" would not be entirely correct.
  - Suggest a wording change: The title element provided serves as the title for the page and the iframe since it does not have its own.

**Comment by WilcoFiers** [comment]
Can be closed after #1379 is merged.

**Comment by WilcoFiers** [comment]
Don't know if this needs another survey. Worth discussing. The title of the rule has been updated.

**Comment by maryjom** [comment]
@WilcoFiers Forgot to add this as a discussion item in the 6 August meeting, but we can briefly discuss and then I can send out a CfC to the group to approve.

**Comment by maryjom** [comment]
@WilcoFiers I sent out a CfC to the group to approve by Thursday.

**Comment by maryjom** [comment]
CfC has completed with no issues brought up. We can now take the rule to the AG WG to approve the update. @WilcoFiers, can we close this issue now?
