### ISSUE TITLE
Resolve "id attribute value is unique" feedback

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag-act#464]
Rule: https://act-rules.github.io/rules/3ea0c8
Survey results: https://www.w3.org/2002/09/wbs/93339/IDisUnique2/results

### Detlev

- [x]  I don't want to hold up things, I just want ACT to ensure that there is a consideration of cases where duplicate IDs may cause no issues.

**Suggestion from TF**: Make sure all examples are actual accessibility issues, such as when used in IDREF and when used on interactive components.

**Comment by maryjom** [comment]
[Survey results](https://www.w3.org/2002/09/wbs/93339/ACTIDValueUnique/results) will be available after the survey due date on 17 September.

**Comment by WilcoFiers** [comment]
Note has been moved. I think this is done.
