### ISSUE TITLE
New rule: All table header cells have assigned data cells

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#469]
The ACT-Rules community group has completed work on "All table header cells have assigned data cells". We would like to see this rule be added to the WCAG ruleset. You can find the rule here:

**Rule title**: All table header cells have assigned data cells
**Rule id**: d0f69e
**Link to the rule**: https://act-rules.github.io/rules/d0f69e
**License**: W3C Software And Document Notice And License
**Implementors**:
- QualWeb
- axe-core

**Comment by maryjom** [comment]
Created [survey](https://www.w3.org/2002/09/wbs/93339/ACTTableHeaders/) due 6 August.

**Comment by maryjom** [comment]
Survey completed on 6 August. The TF had comments documented in [Issue 476](https://github.com/w3c/wcag-act/issues/476).

**Comment by WilcoFiers** [comment]
Closing, we have a separate feedback issue for this.
