### ISSUE TITLE
New rule: Object element has non-empty accessible name

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wcag-act#470]
The ACT-Rules community group has completed work on "Object element has non-empty accessible name". We would like to see this rule be added to the WCAG ruleset. You can find the rule here:

**Rule title**: Object element has non-empty accessible name
**Rule id**: 8fc3b6
**Link to the rule**: https://act-rules.github.io/rules/8fc3b6
**License**: W3C Software And Document Notice And License
**Implementors**:
- Alfa (Siteimprove)
- axe-core (Deque Systems)
- QualWeb (LASIGE, Faculdade de Ciências da Universidade de Lisboa)

**Comment by maryjom** [comment]
[Survey](https://www.w3.org/2002/09/wbs/93339/ACTObjectName/) was created, due 6 August.

**Comment by maryjom** [comment]
Discussed at the 6 August meeting - see [minutes](https://www.w3.org/2020/08/06-wcag-act-minutes.html#t04). The conclusion was there are some comments to address before publishing. WIll open a new issue.

**Comment by WilcoFiers** [comment]
Closed by #479.
