### ISSUE TITLE
Improving format for rules with alternative in Applicability and several corresponding Expectations.

### ISSUE THREAD

**Issue by Jym77** [w3c/wcag-act#548]
We've had several cases in the past where an Applicability ends up as an alternative and the rule is having two expectations to deal which is case. A recent case can be found in [this fix on Meta viewport rule](https://github.com/act-rules/act-rules.github.io/pull/1994/files#r1269543499).

This often leads to wonky expectation that rephrase the Applicability:
> Applicability: each element for which either (condition A) or (condition B)  [note: A and B are not mutually exclusive]
>
> Expectation 1: For each target, either (condition A) does not hold, or (some extra test about A)
> Expectation 2: For each target, either (condition B) does not hold, or (some extra test about B)

This expectations tend to be super wonky because it requires some thinking to figure out why we need to recheck the condition, and especially why it is OK that the condition does not hold.

---
One solution to streamline this is to split the rule (one targeting (condition A) and checking Expectation 1; one targeting (condition B) and checking Expectation 2). But that dilutes the check and make it harder to understand it and see how the rules goes together.

> Rule A:
> Applicability: each element for which (condition A).
>
> Expectation: For each target, (some extra test about A)
>
> Rule B:
> Applicability: each element for which (condition B)
>
> Expectation : For each target, (some extra test about B)

These two rules can be grouped together in a composite rule (requiring both to not fail), but since we do not have nested composite rules, this is a bit "wasting" the composition.

---
I think it would be nice to extend a bit the format with the syntax:
> Expectation 1: For each target [where (condition A)], (some extra test about A)

with the implied semantics that the expectation is satisfied for targets when the [where …] clause is false. This would only be allowed when there are several Expectation, and we could likely require that each test target matches at least one [where …] clause.
This is currently not possible because such an expectation doesn't say what to do for targets where (condition A) does not hold.
 ([where …] might be a bad word to use given we also want to use it for state transitions)

---
Some cases I remember.

The one sparkling this is:
> Applicability: meta viewport defines either `user-scalable` or `maximum-scale`
>
> Expectation 1: For each test target, either `user-scalable` is not defined or it is at least …

I  think it would be more readable as "For each test target where `user-scalable` is defined, …" It would be more straightforward in the logic.

Another one I remember:
> Applicability: each element which is either visible or included in the accessibility tree
>
> Expectation 1: For each test target, either it is not visible or (some stuff about visibility)

Here also, I think it would be much more readable as "For each visible test target, (some stuff about visibility).

**Comment by WilcoFiers** [comment]
I think the rule should just be split. Anything we do to put two related tests into a single page complicates the logic of it. Happy to bring this to TF for further discussion though.

**Comment by Jym77** [comment]
I'm happy with splitting rules. I guess we should take care to mention the other rule as related in the Background, though.
Closing this.
