### ISSUE TITLE
Section 6.2: Data Output - Outcome: Drop cannot tell and add non-applicable

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag-act#69]
From Alistair Garrison: Under 6.2 - I would remove "Cannot tell" (as it conflicts with writing automated tests - if you cannot tell re-write the test!)  And, I would include "Non-applicable".

**Comment by WilcoFiers** [comment]
RESOLUTION: Add a note that cantTell results should be limited to semi-automated rules
