### ISSUE TITLE
Migrate to w3c/respec from bikeshed

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#79]
https://github.com/w3c/respec/wiki

- Reach out to Mike Cooper with questions

- Meet with Shadi to do a walkthrough before migrating fully.

**Comment by moekraft** [comment]
Investigating.

**Comment by WilcoFiers** [comment]
@moekraft @nitedog I don't actually think we'll be doing this. Any objection to closing this ticket?

**Comment by nitedog** [comment]
Yeah, fine by me.
