### ISSUE TITLE
Clarify proof of compliance with absence of violation

### ISSUE THREAD

**Issue by cpandhi** [w3c/wcag-act#8]
The issue is linked to Michael's comment on the review - https://www.w3.org/2002/09/wbs/35422/ACT_DPUB_Review_Nov_2016/results

**Comment by cpandhi** [comment]
"In some cases absence of violations may be proof of compliance..." is not something I think we can be sure enough of to state.
This issue needs assignee.

**Comment by WilcoFiers** [comment]
Issue resolved with #8.
