### ISSUE TITLE
Investigate Va11yS to see if testcases can be updated

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#89]
Create a JSON file that can refer to each test case following the format , http://lists.w3.org/Archives/Public/public-wcag-act/2017Apr/0020.html

**Comment by moekraft** [comment]
Can we apply this format to [Va11yS](https://ibma.github.io/Va11yS/)?

**Comment by moekraft** [comment]
Charu and I met on June 2 to discuss. Will schedule a call with Wilco to discuss some challenges.

**Comment by moekraft** [comment]
Discussed with Wilco. We are holding off on this activity until we revisit the rule format.

**Comment by WilcoFiers** [comment]
Stale issue, not directly relevant to ACT so I'm closing it.
